### ISSUE TITLE
[Item] add inverted variation

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#109]
Add an inverted variation of item.

**Comment by lubber-de** [comment]
Is this really needed? By default all 3 backgrounds for item (`item`,`content`,`extra`) are either `none` or `transparent`. So if the body background will be set black, then it works out of the box,

An item is basically only some layout container, rather than a design element.
All possible elements within an item need to be set to interverd separately anyway if desired by the developer.

Of course we can offer 'inverted item` which would just set the background to black by default, but nothing else is needed then IMHO.

Did you have some other behaviour in mind?

**Comment by lubber-de** [comment]
Ok, i'll prepare a little PR. I just recognized some `color` values have indeed default (black) settings within item (but still most default values are again empty string by defaut (which is invalid CSS anyway btw, We should set those empty strings to `inherit` instead?)

**Comment by hammy2899** [comment]
I was thinking if an item was inverted the text for example would be white instead of black. 

In this case (below) this is a list of items inside an inverted segment.
![image](https://user-images.githubusercontent.com/11588822/47884851-52909580-de2a-11e8-9740-f9e6e505f661.png)

**Comment by lubber-de** [comment]
Fixed in current Release https://github.com/fomantic/Fomantic-UI/tree/2.6.4
