### ISSUE TITLE
Add fomantic to cdnjs

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#110]
Create a PR to add Fomantic to CDNJS https://github.com/cdnjs/cdnjs

**Comment by exoego** [comment]
I would like to try this, since it help potential users to try FUI without hassle of build.

BTW, It seems that there is a popularity requirement: at least `200 stars` or `800 downloads per month`.
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library

As of 2018-10-29, FUI has
* 97 stars 😞 
* Roughly over 800 downloads per month 😃. According to Downloads info at https://www.npmjs.com/package/fomantic-ui

Perhaps it is better to gain more SUI users' attentions and contributions to FUI.

**Comment by hammy2899** [comment]
@exoego https://github.com/cdnjs/cdnjs/pull/12942

**Comment by ColinFrick** [comment]
Fomantic UI is now available on cdnjs: https://cdnjs.com/libraries/fomantic-ui
