### ISSUE TITLE
Possible change in brand identity for v3?

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#1125]
This will most likely come as a shock to most people however please read the full issue before leaving a comment.

I also want to make clear this is not a confirmed decision which is why we are opening this issue in the first place. This is a community focused project which is why we want YOUR feedback and thoughts on the topic.

---

I recently had a catch up call regarding v3 (https://github.com/fomantic/Fomantic-UI/issues/319) with the core team (@fomantic/maintainers) and the topic of renaming the project was brought into the conversation and we discussed this for quite some time. We agreed this would have a lot of benefits but we also discussed some cons. We also agreed to bring this into public knowledge to get your feedback.

If you are wondering what some of the pros and cons were we discussed this is a list of a few (not complete)

Pros:
  - The project won't have a native stigma from being a fork of Semantic-UI.
    - Semantic-UI has grown a stigma over the past few years because of it's inactive development.
  - It allows us to give the framework a fresh start with the release of v3 as it's own entity which isn't associated with Semantic-UI.
  - The current name "Fomantic-UI" is confusing for some people.
    - Some people spell it wrong with the most common error being "**Form**antic-UI".
    - Others pronounce it wrong because lets face it "Fomantic" isn't a word.
    - It is difficult for none native English speakers because it's not a word making it hard to translate.
  - People find it hard to discover Fomantic-UI and a lot of current discovery is done via word of mouth.

Cons:
  - People will be confused if they are not informed of the change.
    - We discussed a few ways we could solve this issue with methods like Advertising etc. but we would like to get your input.
  - We will lose trust and reputation of the brand "Fomantic-UI".

As I said above this is not a complete list of pros and cons however the cons I have listed have huge impact.

So you may be wondering what the new name will be (if we go ahead), well we don't know so we are asking for suggestions, time to get creative 🎉 

We don't have a big list of requirements for the name however this is a few notes you should think about when posting a suggestion.

  - Try and make the name represent the project and our goals as a platform.
  - Try and be creative don't make it similar to other frameworks and don't be generic.

I've come up with 2 names
  - lexical
  - syntactic

Why these names? Well They are both names which are unique but also the definitions of both words are linked to linguistic semantics which of course is the fundamental feature of Fomantic-UI. However 1 issue I have with "syntactic" is it sounds some what similar to "semantic".

---

So what are your thoughts, do you love the idea or hate it? Let us know we are eager to hear your feedback and if you have any suggestions leave a comment and lets have a discussion about it 😃

<br />
<br />
<br />

P.S. If your wondering what "Fomantic" means/how I came up with the name its quite simple. The project is a fork of Semantic-UI so we take the first 2 letters of **Fo**rk and replace the first 2 on **Se**mantic-UI and you get Fomantic-UI 😉

**Comment by victorcerutti** [comment]
Are there any possibility to get back to the "semantic ui" name ?
That's what would make more sense, even if of course it's only dependent of your will

**Comment by hammy2899** [comment]
@victorcerutti Currently know as we have no authority or way to make changes to the SUI repo or GitHub org. Also as I said SUI has a large stigma which I think most of use agree we should try and move away from.

However as it says on our repo [README](https://github.com/fomantic/Fomantic-UI/blob/fb9ec3372674509e668110a670de59c6471145d4/README.md) we have the intent to merge back into the SUI repo but of course we would need to take over the project to do that which looks less likely as the days go on.

**Comment by fridzema** [comment]
My vote goes to just fomantic without the UI :)

**Comment by maidzen** [comment]
moving on is the right choice in my opinion SUI is most likly dead and even if an update arrives now how should we trust him that he not leaves for another year.

Instead of finding a synonyme for semantic we should maybe focus on why it is "semantic" in the name
i would say something like "meaningfull UI" or "Suggestive UI"

**Comment by GammaGames** [comment]
> People find it hard to discover Fomantic-UI 

Even of you google “fomantic ui” it almost  always brings up the site for semantic for me, which makes it harder for people to find anyway

**Comment by prudho** [comment]
When @hammy2899 started forking SUI and bringing interested people in the freshly created Discord, my first ever comment was: "Fomantic ? What does that mean !?"... So yeah, confusing name... But I stayed anyway 😄 

This idea of "rebranding" the framework is IMHO a great opportunity and will allow us to have a better visibility and to move away from its defunct's relative.

Since I really suck as naming things, I'll just throw a few ideas that crossed my mind during a synonym search:
- Natural UI
- Intrinsic
- Prose

**Comment by whoisryosuke** [comment]
I would just stick with the name.

All the branding and SEO you’ve built up gets thrown away when you change the name. Suddenly all the blog posts about Fomantic become irrelevant. 

If the purpose is to still maybe not be merged back into SUI, but get used as it’s predecessor, you should keep some semblance of the original name. 

SUI may have a stigma with some, but the point of *this* brand is to reignite the passion and love people have for the framework that was simply lost due to lack of development. I personally got hyped seeing that people were still creating new components and not giving up. If I saw this as some other crazy weird name with all the SUI styling, I’d think it was some knockoff. 

The point of a good brand is to reinforce itself, even if the audience doesn’t understand it fully. There are plenty of brands you’ll hear people mispronounce, while the true fans know the right way (it’s not Ahdeedus, it’s Ah di duz for Adidas).

**Comment by lubber-de** [comment]
> All the branding and SEO you’ve built up gets thrown away when you change the name. Suddenly all the blog posts about Fomantic become irrelevant.

That's a very important concern! I am not a SEO expert, but it took over a year now to somehow get fomantic known and i am afraid that...

> Even of you google “fomantic ui” it almost always brings up the site for semantic for me, which makes it harder for people to find anyway

... this is going to happen again with a completely new name

> My vote goes to just fomantic without the UI :)

> Natural UI

Maybe we could think about following a (long) strategy to keep both for a while and slightly get the community used to a new name. 

### Step 1
fomantic - semantic UI fork using natural classnaming

### Step 2
fomantic - the Natural UI just like Semantic UI was

### Step 3
fomantic - the Natural UI 

### Step 4
Natural UI

**Comment by hammy2899** [comment]
@lubber-de I like the idea of changing over time however I think there is some caveats, at what step do you rename the repos and packages. Remember renaming npm packages would lose all of the current versions associated with the old name since you can't rename a package you can only publish it as another.

**Comment by Atulin** [comment]
I also vote for just dropping the "UI" part.

Also, the problem with most of the proposed names is that they are actual words. Yes, it's good because it's easy to remember, but it's bad SEO. If I google "Prose", I'll get results that define whtat prose is. If I Google "Essential UI", I'll get links to courses and tutorials on essential UI elements, and so on.

"Fomantic" not being a word is actually an advantage, IMO. And dropping "UI" should stop Google from suggesting "did you mean Semantic UI?"

**Comment by filozof595** [comment]
If I'm correct you plan to rewrite most (if not all) of the components, remove jquery, add some new components etc...

Why not just start over...? Make a completely new freamwork that takes it's inspiration from Semantic-Ui. 

I know that this would require a lot of work to do but I think it's the best way.

For the name, I like Natural or Lexical.

**Comment by maidzen** [comment]
> If I'm correct you plan to rewrite most (if not all) of the components, remove jquery, add some new components etc...
> 
> Why not just start over...? Make a completely new freamwork that takes it's inspiration from Semantic-Ui.
> 
> I know that this would require a lot of work to do but I think it's the best way.
> 
> For the name, I like Natural or Lexical.

Losing the spirit of what semantic has would mean losing a lot of users because most are here to have an "updated" version of semantic

**Comment by filozof595** [comment]
> Losing the spirit of what semantic has would mean losing a lot of users because most are here to have an "updated" version of semantic

Why would you loose the spirit of Semantic? I was just saying that you can use a new name and brand it as a new freamwork that is inspired by Semantic.

Just like you created Fomantic in the first place.

At the end, the users like Semantic because of the easy syntax and the simplicity of the framework. Just make sure you have all that in the v3 and you would have a lot more users regardless of the name or branding.

**Comment by Bradley-H** [comment]
my opinion would be to keep it, taking it and rebranding it would almost be a slap to the face to the orginal creator of Semantic UI.

**Comment by victorcerutti** [comment]
My major concern would be SEO too
If you change the name to anything other than semantic or fomantic you will lose the SEO benefit of the community that asked for question and got answers.
The answer to your issue could be on stackoverflow with the name "semantic UI" or "fomantic UI" and you wouldn't find it with the new name. Currently I always have to google both term to optimize my chance of finding a solution to a problem.

**Comment by maidzen** [comment]
@filozof595 that's reasonable i misunderstood it as "drop the work and start over" because "keeping some inspiration" sounded just like nothing :)

**Comment by mpoonuru** [comment]
I respect you. You did a great job. I accept whatever the name you Decide. I believe that everybody accepted fomantic-UI and using it. I believe that the new name decided by you will be accepted. Thanks for considering us and involving us in this project.

**Comment by romaninsh** [comment]
- fantastic ui

**Comment by jvalteren** [comment]
Thanks for asking the community!
I agree with both @whoisryosuke and @Atulin.

**Comment by keesee** [comment]
As Fomantic UI I think the project will always just be seen as a fork of SUI.  A new name and a new theme with a modern feel for version 3 is just what the project needs, IMHO.   Timed together.
i think the current site, blog. repos etc can stay with messages, depreciation notices or some other interaction that can lead or redirect users to the new name.   Id encourage us to looks forward; not back.

**Comment by mtness** [comment]
Hi there!
Since I always refer to "Semantic UI" as SUI", it would be good to keep this abbrevation, 
just .. make it ... simpler ... simple
SIMPLE UI !!

Simply UI ?

This just came to my mind, so what do you think?

**Comment by willstott101** [comment]
Personally I detest the name `Fomantic UI` but I see no issue with the suffix. I always read Fomantic as Fomatic which is much closer to an English sounding word (just like Formantic would have been). The UI suffix hints at the projects past whilst also actually describes what the project **is**, there's nothing more annoying than trying to figure out what a product actually provides you.

Something like `Lexical UI` would work best for me. It's not the UI that gets google to correct to "semantic ui" it's the whole "mantic ui". I'm in favour of ripping off the plaster and just re-naming now, rather than always living with an awkward name, sure it might cause a bit of confusion, but might also inspire a bit of hype around v3.

**Comment by luki1412** [comment]
Hello,

I think the renaming makes sense, mainly because Fomantic is hard to find. When I found semantic I wanted to install it and it keeps failing through npm so I searched online and that's where they suggested a user with similar problem to use Fomantic instead. But when I searched Fomantic UI, google keeps saying: Did you mean Semantic UI ? Which is the main issue here. This UI is hard to find.

When it comes to the name, I would suggest something like **Symbolic UI**.

Now, does this mean you are going to create a new github repository for the version 3 or can you rename this one? Or perhaps you wish to keep this page intact?

**Comment by Ydot19** [comment]
Suggested Name: **M.U.I**

M: Mignon (_french for pretty_)
U: User
I: Interface

**Comment by hammy2899** [comment]
@Ydot19 users will find that confusing with Material UI but thanks for the suggestion 😃

**Comment by donaggio** [comment]
@Ydot19 There's already a [M.U.I.](http://www.sasg.com/mui/)!

**Comment by JambaDog** [comment]
Synoptic-UI

**Comment by bakeiro** [comment]
What about create semantic UI 3.0 and merge to the original project? like, the repository has a lot of issues, stars, and history, so starting from the beginning with other name, we would need to wait until people know the project

**Comment by prudho** [comment]
@bakeiro we don't own the original SUI repo, so we can't merge to it.

**Comment by 0usssama** [comment]
as i began using semantic and later fomantic ui, the simplicity attracted me more, so for me i think if you rebrand it: **Simple UI**

**Comment by hammy2899** [comment]
Closing as we and I think the community in general have made the decision for which name we should use.

### **Fomantic** 😎

**Comment by kspeakman** [comment]
I didn't see this pointed out. If Fomantic UI is going to continue to exist to support users that depend on it, a simultaneously existing brand of Fomantic (sans UI) is going to be confusing for users. UI users will accidentally find themselves in non-UI documentation from search results, and vice versa. Leading to confused github issues. So be on the lookout for that.
