### ISSUE TITLE
Div Menu dropdown multi column not work

### ISSUE THREAD

**Issue by crewow** [fomantic/Fomantic-UI#1300]
here is test case

https://jsfiddle.net/rs3q10c8/

**Comment by prudho** [comment]
Confirmed.

Happen when dropdown is built from a `div` element. If `select` is used, it works.

**Comment by lubber-de** [comment]
Fixed by #1533 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/suqcb52r/9/

Main problem is: inline-block does not work well with whitespace/line breaks which exists all over the place in a tidy formatted html source (converting select created menu item divs without any whitespace, thats why it was working there.
