### ISSUE TITLE
[Loader] Compatibility broken with Semantic-UI-React

### ISSUE THREAD

**Issue by AKorezin** [fomantic/Fomantic-UI#1357]
Description:
---
Pull request #359 breaks loader inside dimmer with react.

Semantic-UI-React creates additional block inside dimmer:
```jsx
<Dimmer active>
  <Loader />
</Dimmer>
```
creates:
```html
<div class="ui active transition visible dimmer">
  <div class="content">
    <div class="ui loader">
    </div>
  </div>
</div>
```
So loader styles are not applied.

[Link to the source code of dimmer in Semantic-UI-React repo.](https://github.com/Semantic-Org/Semantic-UI-React/blob/2dbab6bec372f3013d4c18448c2600c9d531e378/src/modules/Dimmer/DimmerInner.js#L141)

Should I create an additional issue in Sematic-UI-React?

**Comment by lubber-de** [comment]
Yes, please address this at the SUI React Repo, because also the [SUI Docs for loader](https://semantic-ui.com/elements/loader.html#loader) tell you to create the loader as direct child of the dimmer itself.
The mentioned PR corrects the inheritance for dimmer loaders and we won't revert this.
Instead SUI React should handle dimmer loaders as a separate child instead of wrapping any kind of content it into a separate content div which would still be compatible to SUI.
