### ISSUE TITLE
[Form Validation] `add prompt` method doesn't set error message

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#1374]
The form validation API for 'add prompt' doesn't work as expected. The [documentation](https://fomantic-ui.com/behaviors/form.html#/settings) looks ambiguous which describes two different explanation for 'add prompt' behavior.

## Testcase
Here's the fiddle (https://jsfiddle.net/k1a9w73t/4/). As the fiddle result, the validation methods return the default prompt message regardless of the message which specifies via `form('add prompt')` method. The fiddle uses version 2.7.5.

I tried to test with the latest version. However, the form validation doesn't work at all as the same methods with version 2.7.5. Here's the fiddle that uses version 2.8.4 (https://jsfiddle.net/zfgs590x/).

**Comment by lubber-de** [comment]
According to the source, the `add prompt` behavior is meant to define an **inline** prompt only and only if no other rule is defined already. 

Also the usage of `add prompt` is to provide a field identifier and a message as parameters instead of a rule. Also make sure the `.form()` is called on a form itself, rather than a field directly

See
https://jsfiddle.net/57svq0ko/
![image](https://user-images.githubusercontent.com/18379884/77144138-5d7eb100-6a85-11ea-9dd6-3bd518dcd6c8.png)

**Comment by ko2in** [comment]
@lubber-de Thanks for the hint. The [documentation](https://fomantic-ui.com/behaviors/form.html#/settings) isn't clear enough for this use case, and I was confused because it explains two different usages.

add prompt(identifier, errors) | Adds error prompt to the field with the given identifier
-- | --

add prompt(identifier, prompt) | Adds a custom user prompt for a given element with identifier
-- | --

The first one failed for me, so I tried with the second one which describes to attach to the specific element instead of the form.

I'm not sure how to use `add errors`, because there is no explanation about the structure of `errors` parameter. The doc says array, but no clue how does the errors array look like for this.

That would be nice the documentation includes the example how to use each behavior. Most of them are hard to understand without looking into the source code.

**Comment by lubber-de** [comment]
Docs changed accordingly by https://github.com/fomantic/Fomantic-UI-Docs/pull/223
