### ISSUE TITLE
[Dimmer,Modal] Issues using Modal and Dimmer at the same time:

### ISSUE THREAD

**Issue by n00b42** [fomantic/Fomantic-UI#1402]
# Bug Report
After opening and closing a dimmer, every click on a opened modal that does not close the modal, yields a permanent backdrop even after closing the modal.

## Steps to reproduce
Minimal working issue: https://jsfiddle.net/ca4zhyj5/1/
1. Dimmer is automatically opened
2. Close the dimmer by clicking on it.
3. Open the modal using the button
4. click on the header (or anything but the buttons or the backdrop)
5. then close the modal

## Expected result
The backdrop should be properly hidden as well.

## Actual result
The backdrop overlay remains visible blocking the page.

## Testcase
https://jsfiddle.net/ca4zhyj5/1/

## Screenshot (if possible)
![](https://i.imgur.com/kIhgMQn.png)
![](https://i.imgur.com/GomKXAL.gif)

## Version
2.8.4

## Hint
The click on the modal somehow removes the `dimmed` class from body

**Comment by lubber-de** [comment]
Your separate page dimmer is also a child of body which confuses the modal.

Whenever you have a separate `page dimmer`, you should tell any modal call to reuse that instead of creating a new page dimmer. You can do this by providing a unique class of your page dimmer or an empty string to the `dimmerSettings.dimmerName` value. 

- If the dimmerName is empty, it catches the first existing dimmer in the DOM tree
- If the dimmerName is a unique classname, it will select that dimmer instead

```
$('#mymodal').modal({
	dimmerSettings:{
		dimmerName:'myownpagedimmer' //className, NOT id (!)
	}
}).modal('show');
```

When used, your issue is fixed
See https://jsfiddle.net/lubber/k1b8znhg/1/

**Comment by h0lg** [comment]
> You can do this by providing a unique class of your page dimmer or an empty string to the `dimmerSettings.dimmerName` value.

@lubber-de This doesn't play well with existing dimmer content. E.g. if my page dimmer contains a loading message and a custom loading image, those are be visible south of small modals - which is confusing since the page is not in loading state when opening a modal.
