### ISSUE TITLE
[dropdown with selection] dropdown('clear') removes icon in default text

### ISSUE THREAD

**Issue by tonynamy** [fomantic/Fomantic-UI#1403]
# Bug Report
I used a dropdown with selection and add an icon to the span with 'default text' class. When I clear dropdown with the following JS code,
`$('#example_id').dropdown('clear')`
it removes the icon in the span.

## Steps to reproduce
[https://jsfiddle.net/nubLwr2d/](https://jsfiddle.net/nubLwr2d/)

![Video_2020-04-08_122723](https://user-images.githubusercontent.com/36332025/78741781-3dac2000-7995-11ea-960c-cd2fe92a97c8.gif)

## Expected result
The icon should not be removed.

## Actual result
Dropdown clear removes the icon in default text.

## Version
2.8.4

**Comment by prudho** [comment]
You can get rid of this behavior by moving the icon outside the `default text` div.

Please take a look here: [JSFiddle](https://jsfiddle.net/Luzk198p/).

Fomantic stores the placeholder text as a string into the metadata, and to do so it get rid of any HTML there... I'm pretty mixed to tag this as a bug and provide a fix... what to you think @fomantic/maintainers ?

**Comment by lubber-de** [comment]
Fixed by #1543 See your adjusted jsfiddle here  https://jsfiddle.net/lubber/L8hof4jp/4/

@prudho The placeholder setting, especially when converting select tags, was already supporting HTML and the metadata already stored and kept existing html placeholders. It was just never restored because of the `.text()` usage.

**Comment by tonynamy** [comment]
Thanks.
