### ISSUE TITLE
Calendar in UI does not gets refreshed when eventdates are changed

### ISSUE THREAD

**Issue by sonam1318** [fomantic/Fomantic-UI#1530]
# Bug Report
First time inline calendar loads fine with initialdate and eventdates set, on a external button click, the values of Calendar - initaldate and eventdates array are changed. But it does reflect in UI.

## Steps to reproduce

1. Assign Initial date and EventDates to an inline Calendar 
2. Change above two values in code on a button click.
3. Calendar in UI does not change
4. Refresh method does not work too

## Expected result
Calendar should show the new month and events.

## Actual result
Calendar does not change anything in UI

## Version

2.x.x

**Comment by ko2in** [comment]
Please provide [jsfiddle](https://jsfiddle.net/) with your implementation. So, we can looks into it.

**Comment by lubber-de** [comment]
Here is a jsfiddle to play with, but i cannot reproduce the behavior, because it works  as expected
https://jsfiddle.net/lubber/75Leq9n4/18/
@sonam1318  What you need to know:
- `initialDate` can only be set when the calendar is initialized for the first time. If you want to change the date later, use the `set date` bahavior
- For updates to the inline calendar when after changing settings, call the `refresh` behavior
![inlinecalendareventupdate](https://user-images.githubusercontent.com/18379884/85232288-2e6a3980-b3fe-11ea-8642-8d4aad825753.gif)

**Comment by sonam1318** [comment]
@lubber-de Thanks a ton for the information and the working example.

It worked! I was not using "set date" and settings before to update it.
