### ISSUE TITLE
[button] toggle button with a different background-color

### ISSUE THREAD

**Issue by bartocc** [fomantic/Fomantic-UI#1583]
# Feature Request

AFAICT, `.ui.toggle.button.active` uses `background-color: @positiveColor;`

Would it be possible to choose a custom background-color?

**Comment by lubber-de** [comment]
Sure, just change from `@positiveColor` to whatever you need , like `rgb(128,64,64)`

**Comment by lubber-de** [comment]
🤔 I think we should use a dedicated variable there for easier theming....i'll prepare a PR

**Comment by bartocc** [comment]
I should have been more precise in my question. The idea I had in mind was to be able to do so without theming, but with predifined CSS classes.

Something like this or similar: `<button class="ui toggle toggle-red button">my button</button>`

**Comment by lubber-de** [comment]
Understood, but difficult, because this would break the namig logic of FUI so far, because a `ui red toggle button` would appear in red without being toggled (and always green when active) and the current implementation does not know if `red` is supposed to be the general color or the toggle color.
Yes, using something like you suggested `toggle-red` would fix this but, as mentioned, breaks the current usage.
@fomantic/admins  What do you think? This would be more of a v3 design decision?

As a workaound you can change the behavior with a bit of custom css
```css
.ui.active.toggle.button {
  background-color: blue !important;
}
```
See https://jsfiddle.net/lubber/vL4he5fd/4/

**Comment by lubber-de** [comment]
Here is another workaround without extra css. Replace the classname `active` by the desired color name
```javascript
$('.ui.toggle.button')
    .state({
      className: {
        active   : 'purple'
      }
})
```
![simpletoggle](https://user-images.githubusercontent.com/18379884/87698778-3cf50800-c794-11ea-8c67-6575829c0c4f.gif)

See https://jsfiddle.net/lubber/vL4he5fd/15/

**Comment by ko2in** [comment]
Toggle represents two different outcomes. So `toggle red button` makes no sense in my opinion. It would be confused in which situation that the toggle should turn into red.

IMHO, the toggle should be unique and standardize across your UI, like different countries has their standard of the plug types (some use two pins, some use three pins and so on). I'm not sure where do you use two different colored toggle button at the same time. It's not even good for user experience.

**Comment by bartocc** [comment]
I think I agree with you @ko2in , two different active colors for toggle buttons on the same site does not really make sense.

If I really need this, I'll use @lubber-de workaround 👍 

And in the meantime, I'll use the theming to change the active color
