### ISSUE TITLE
[Dropdown] disabled + tab key

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1605]
# Bug Report
When a dropdown with search selection is disabled, the search input is available with tab key

## Testcase
https://jsfiddle.net/dutrieux/pzh25rg1/

## Screenshot (if possible)
![bug_dowpdown](https://user-images.githubusercontent.com/1622751/88456015-a0f58b80-ce7a-11ea-8f06-d6ad1f0ba109.gif)
## Version

2.8.6

**Comment by lubber-de** [comment]
Fixed by #1606 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/gcweburm/

The same happened to disabled calendar fields, which the above mentioned PR also fixes 🙂

**Comment by dutrieux** [comment]
I would have thought you would have used the readonly attribute rather than disabled.
I don't think it use, but with disabled, the value of input search is not send to the server when the form is submit rather than readonly

**Comment by lubber-de** [comment]
> I would have thought you would have used the readonly attribute rather than disabled.

Using `readonly` will not prevent to enter the input field while pressing tab. In case of an empty dropdown field, this would autoselect the first entry when pressing tab again (and, even worse, in case of calendar, would still open the calendar popup)

![disabledtabinput_reaonlycheck](https://user-images.githubusercontent.com/18379884/88467707-1c3a5a00-ceda-11ea-8dd1-30df6f17f3f6.gif)

However, i fixed it by using `tabindex` instead of `disabled` now. Same effect, but the value will be submitted as the input field itself is not disabled anymore

See your example using the tabindex approach here now: https://jsfiddle.net/lubber/gcweburm/1/
