### ISSUE TITLE
[Sidebar] "pushable" should add overflow-y: hidden?

### ISSUE THREAD

**Issue by layershifter** [fomantic/Fomantic-UI#1607]
# Bug Report

Based on https://github.com/Semantic-Org/Semantic-UI-React/issues/3884.

## Steps to reproduce
1. Open a repro Fiddle
2. Mention that scroll exists for `bottom` variation (for `top` everything is okay)

## Expected result
No scroll

## Actual result
Scroll exists

## Testcase
https://jsfiddle.net/dzpc73rb/5/

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/14183168/88527576-c1018800-cffd-11ea-83bd-c47fe6874dcf.png)

## Version
2.8.6

**Comment by layershifter** [comment]
Folks, I am not sure that it's a SUI/FUI itself, but I would to hear your opinion 🙏

**Comment by ko2in** [comment]
@layershifter `overflow-x` is for horizontal scrolling. Are you talking about to support `overflow-y: hidden`?

**Comment by layershifter** [comment]
@ko2in Oops, good catch. A typo in header, fixed 👍

**Comment by lubber-de** [comment]
I played around with that for some time now. I also came to the conclusion that the overflow-y:hidden approach seems legit. However, it has to be limited to `:not(body)`, otherwise the main window cannot be scrolled anymore.

Technical reason is the `translate3d()` setting to hide the sidebar. For `left`/`right` the `overflow-x` is already hidden. For `top` the browser won't add the sidebar content to the pushable div height, because translate3d() gives a negative y position to be show off canvas.
For `bottom` however the `translate3d()` is 100% for y which lead the browser to calculate its content to the pushable parent div.
However, the browsers do not do this when the pushable element is `body` .

I tried several changes to get this fixed otherwise:
- changed to `translate()` instead of `translate3d()` -> No difference
- removed `translate3d()` from the hidden sidebar. -> That indeed removed the scrollbar when no animation took place, but was still visible again when the sidebar slide-in/out animation took place. 
- changed from `translate3d()` to `scale()` -> No scrollbar anymore but completely different visual experience (ugly IMHO) 

I added the proposed change by #1622

**Comment by jenUnderscore** [comment]
This change broke my app. Pushable is coming from sidebar (left) and this change erroneously prevents the contents of the pushable contents from scrolling.

**Comment by lubber-de** [comment]
Please provide a jsfiddle with your use case and we'll see what we can do.

**Comment by jenUnderscore** [comment]
Sure!

Here is an example of how it behaves in our app. 
https://jsfiddle.net/92bhuazx/

This fix made some assumptions on the type of content that would be part of contextual pushable, specifically that it would not be a fixed height with scrollable content. I believe the original Semantic-UI had the correct implementation since the expected default behaviour of a div element is overflow-y: auto;  

Perhaps the fix is to switch the overflow-y to hidden only when the trigger has been clicked?

We have the "dimmed" css class we can play around with on the pusher element.... perhaps something similar for the pushable would be nice too? Like a "pushed" class or something... 

Perhaps setting the translate3d(0, 0, 0); by default and switching it to translate3d(0, 100%, 0); at the toggle part of that fix for the issue with bottom sidebar. 

... it's a tricky problem, for sure!
