### ISSUE TITLE
[Image] "link" images are not centered

### ISSUE THREAD

**Issue by layershifter** [fomantic/Fomantic-UI#1608]
# Bug Report

The issue was originally reported in https://github.com/Semantic-Org/Semantic-UI/issues/4708 and then in https://github.com/Semantic-Org/Semantic-UI-React/issues/3953.

## Steps to reproduce
1. Open a Fiddle
2. Mention that an image on bottom is not centered.

## Expected result
All images are centered.

## Actual result
Link images are not centered.

## Testcase
https://jsfiddle.net/epc4nL2a/

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/14183168/88532451-eb0a7880-d004-11ea-86a0-5f1c6c3645c0.png)

## Version
2.8.6

**Comment by ko2in** [comment]
@layershifter , You don't need to specify `centered image` to your link. Here's fiddle: https://jsfiddle.net/sqr50cjh/

**Comment by layershifter** [comment]
@ko2in As I see you moved all CSS classes to `img` instead of `a`, however an example in SUI/FUI docs does the opposite: https://fomantic-ui.com/elements/image.html#image-link.

It feels confusing...

**Comment by ko2in** [comment]
@layershifter You're right that the doc looks confusing. I guess you should provide specific rule to your link to display as block if you're willing to present the image as a link and align center.

Currently, the center alignment only applies to `img` because it's displaying as block element as standalone. Maybe, we should explicitly set as block element for all `centered.image`.

I'll check later if I should submit PR for that.

**Comment by lubber-de** [comment]
@ko2in here is a quick jsfiddle. Providing `display:block` for any centered image seems to fix the issue.
However, for image groups it still does not work
https://jsfiddle.net/lubber/vu4bh3g1/5/

**Comment by ko2in** [comment]
@lubber-de Maybe, this should work: https://jsfiddle.net/spq9kLd3/

**Comment by lubber-de** [comment]
@ko2in Looks good! Will you prepare a PR?

**Comment by ko2in** [comment]
Yes. I'll do more investigations and prepare PR.

**Comment by lubber-de** [comment]
Fixed by #1618
