### ISSUE TITLE
[Header] collision with `content` icon

### ISSUE THREAD

**Issue by layershifter** [fomantic/Fomantic-UI#1620]
# Bug Report
Comes from https://github.com/Semantic-Org/Semantic-UI-React/issues/3925.

An icon receives additional CSS:
![image](https://user-images.githubusercontent.com/14183168/88810732-09fc3c80-d1b6-11ea-9529-dd9f963369e1.png)

## Expected result
Icons on the same line.

## Actual result
See screenshot.

## Testcase
https://jsfiddle.net/hr8nuxy1/2/

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/14183168/88810629-e638f680-d1b5-11ea-8321-51df486b69a5.png)

## Version

2.8.6

**Comment by ko2in** [comment]
It's also related to #1619

**Comment by lubber-de** [comment]
This is really difficult, because the only general fix would be to change everything from `.content` to `.content:not(.icon)`
Unfortunately there already exist more than 100 selectors over the whole library which are using `.content {`, over 300 selectors for just `.content`  😳 
Even the `.line` selector (#1619) is available ~ 50 times in placeholder.less

Workarounds to avoid those massive changes:

- Use `hamburger icon` alias instead of `content icon` 
- For `line` i suggest to use alias names for `line graph icon` and `chart line icon` (maybe make one word out of them `linegraph` and `chartline` (not existing, so we might add this to icon.overrides)

On the other hand: We already had the discussion about optimizing icon names as a proposal for v3 and agreed to use data attribute `data-icon` instead of classnames as we already use for emoji (data-emoji), but this will be a breaking change. I thought about making usage of class vs data-icon optional at compile time, but some modules have harcoded templates creating icons

@hammy2899 , God of the FUI icons 😄 , what do you think? Also @fomantic/maintainers

**Comment by hammy2899** [comment]
Quick look it seems like changing the icon names would be the best shout but I will take a better look once I'm on my PC

**Comment by ko2in** [comment]
I postponed to fix this issue according to the discussions above. I was intended to fix by using `:not` pseudo, and now it doesn't look a good idea. I'll check again if we've decided how to fix with the best solution.

**Comment by lubber-de** [comment]
We don't need to implement all the [above mentioned ](https://github.com/fomantic/Fomantic-UI/issues/1620#issuecomment-665829045)(un-) necessary overhead changes because
FUI as well as SUI (!) already have several alias names for the `content` icon already, which fixes the issue

|SUI|FUI|
|-|-|
|bars<br>sidebar|bars<br>sidebar<br>hamburger|
|https://jsfiddle.net/lubber/a9308kge/2/|https://jsfiddle.net/lubber/a9308kge/|
