### ISSUE TITLE
Form - onSuccess,onFailure not called properly / firing correctly

### ISSUE THREAD

**Issue by barelyAWesome** [fomantic/Fomantic-UI#1677]
# Bug Report
The onSuccess and onFailure callbacks of the form module do not get called except on submit, even when the "on:" setting is changed to blur or change.

## Steps to reproduce
1. Create form html element
2. Instantiate in JS with "on: change" or "on: blur"; add onSuccess callback with simple console.log

## Expected result
The callbacks should be fired in accordance with the "on:" setting. Submit by default, but if set to blur or change, then it should fire on blur or change.

## Actual result
Only fires on submit regardless of the "on:" setting.

## Testcase
https://jsfiddle.net/AdamH2017/91puwz6q/

**Comment by ko2in** [comment]
That's expected behavior. `onSuccess` callback triggers only when the form submitted. It doesn't trigger according to `change` or `blur`. Maybe `onValid` callback is what you're looking for. See this fiddle (https://jsfiddle.net/ko2in/4npmybuf/8/)

**Comment by AdamHWeiss2017** [comment]
> That's expected behavior. `onSuccess` callback triggers only when the form submitted. It doesn't trigger according to `change` or `blur`. Maybe `onValid` callback is what you're looking for. See this fiddle (https://jsfiddle.net/ko2in/4npmybuf/8/)

To me that's unexpected. Specifically, the documentation refers to the context for onSuccess as 'form', whereas onValid is for 'field'. Therefore onValid gets called when any field passes validation rules (for each valid field, as expected), not when all validation rules pass.

Further, the documentation does not specify that those callbacks are only fired on submit, but instead says 'after a specific behavior'. It is strange and ineffective to me that the "on:" setting will only alter the field-context callbacks but not the form-context callbacks. 

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/8966926/93510107-b91fdf00-f8ee-11ea-9095-3211b8b8dc5c.png">

The intended use case is to disable the submit button until all fields are valid which is not entirely achievable under the current setup. Allowing for the form-context callbacks to be called based upon the "on:" setting provides more flexibility.

Alternatively, a property that could be set on those callbacks to determine the event that triggers it would be sufficient as well.

**Comment by ko2in** [comment]
The form doesn't have `change` or `blur` event as it's nature. It has only `submit` and `reset` events. The `on` settings for `change` and `blur` is to bind the event to each field with their validation rule.

The form can only validate it's fields inside when it's submitted and thus trigger `onSuccess` callback if all fields passed validation or `onFailure` otherwise. I don't see any reason to validate all fields whenever each field with `blur` or `change` event occur and trigger `onSuccess` which doesn't make sense to me.

In your use case, you can check with API `form('is valid')` inside `onValid` and `onInvalid` callbacks and control the state of submit button. Here's fiddle (https://jsfiddle.net/ko2in/oh4jtqLm/1/)

**Comment by AdamHWeiss2017** [comment]
I see what you are saying. My only qualm is that `onValid` and `onInvalid` are called for each field, as is their intended behavior. So changing one field causes `onValid` to run for every field. In the case of a login form with 2 fields that's not so bad, but a form with 10 fields would trigger the callback 10 times for each `change` or `blur`. 

To me it makes sense to have the `on:` setting propagate to the calling of the `onSuccess` and `onFailure` functions, such that they are called only once for each trigger rather than once per field for each trigger. Then the form size does not impact the number of calls for each form event.

**Comment by ko2in** [comment]
How can you know whether the fields are valid or invalid without validating them? Lets say, you've three fields in your form, you invoke the form module with `change` or `blur` with `on` setting. And you manipulate the value in one field, then how do you know the other fields are valid or invalid without validating them?

**Comment by AdamHWeiss2017** [comment]
Naturally you have to validate fields to know if they are valid... what I am suggesting is really that `onValid` and `onInvalid` should be modified to call `onSuccess` and `onFailure` with the same trigger as the fields, not only the submits. If `onValid` fires for each change or blur, then it should call `onSuccess` or `onFailure` accordingly.

**Comment by ko2in** [comment]
`onSuccess` or `onFailure` can only trigger if all fields are valid or invalid. And you still ended up to validate all fields with `onChange` or `onBlur` to trigger that since `onValid` and `onInvalid` knows only about the specific field, not the other fields.

If they should call `onSuccess` or `onFailure`, they need to check whether the other fields are valid or not and call `onSuccess` or `onFailure` accordingly.

I'm not sure about the other FUI maintainers, but for my opinion, I don't like to support the form API to validate all fields with `onChange` or `onBlur` which is confusing and everyone knows that `onChange` and `onBlur` belongs to the specific field, not the form.

You can still achieve your implementation with `onValid` or `onInvalid` callbacks as my fiddle (https://jsfiddle.net/ko2in/oh4jtqLm/1/).

**Comment by zwcloud** [comment]
Not quite related, but this should be added to the docs.
https://stackoverflow.com/a/34718724/3427520

> It appears that by having two separate .form() method calls, it creates two validation checks that execute independently from each other. So the first call without rules will always be successful.

I thought calling `form(a).form(b)`  will combine `a` and `b`. But in practice it's not true.

**Comment by lubber-de** [comment]
The "onSuccess is  called although form is invalid" is fixed in Fomantic
See https://jsfiddle.net/3gt4yuzo/

Otherwise this behavior logic is the same for all modules. If you run `.form` (or (.modal/.dropdown...) a second time on the same DOM node and _also_ providing a complete new settings object, then it's re-instantiated.

You can, however, reuse the previous instantiated form by using behaviors instead of providing another config object.
```javascript
$('.ui.form').form({
  whatever: true
]).form('is valid')
```
So, in the original example you would have just combined both form call settings into one and the issue is completely solved
https://jsfiddle.net/3gt4yuzo/1/

I have to admit, the difference is not completely clear in the docs. However the usage of behaviors is described in every module
https://fomantic-ui.com/behaviors/form.html#behaviors

I think a simple hint message to all behavior sections should be sufficient.
You are welcome to provide a PR in the docs repo https://github.com/fomantic/Fomantic-UI-Docs 😉
