### ISSUE TITLE
[Dropdown] JavaScript error when adding to dropdwon while hideAdditions = false

### ISSUE THREAD

**Issue by kamalkemo** [fomantic/Fomantic-UI#1679]
# Bug Report
when allowAdditions is true and  hideAdditions is  false , Javascript error occurs when clicking the new added label
![2020-09-20_0-44-42](https://user-images.githubusercontent.com/6898113/93690609-918d6a00-fada-11ea-8000-65c68360101d.gif)

## Steps to reproduce
1. create a new dropdown with options `{ allowAdditions: true, hideAdditions: false}`
2. add a new option
3. click the new added option
4. see the error 

## Expected result
shouldn't get an error

## Actual result
 Uncaught TypeError: Cannot read property 'trim' of undefined

## Testcase
http://jsfiddle.net/kamalkemo/bwhsrvdf/

## Screenshot (if possible)
![2020-09-20_0-44-42](https://user-images.githubusercontent.com/6898113/93690628-e3ce8b00-fada-11ea-9a74-d6ddaa9d614a.gif)

## Version
2.8.7

**Comment by TheJltres** [comment]
The bug is caused beacause fomantic does:
1) Handles click event and deletes user adition
2) Handles `forceSelection` function and calls click again

The problem is when `forceSelection` calls click again user adition is already deleted by the first click event.

If `forceSelection` is set to false, no error is shown.

**Comment by lubber-de** [comment]
Fixed by #1681

**Comment by kamalkemo** [comment]
Looks great , Thanks!
