### ISSUE TITLE
Range Slider does not fill range between buttons

### ISSUE THREAD

**Issue by eazrael** [fomantic/Fomantic-UI#1723]
In dist/components/range.css in line 40 the width: 0; is not commented out as in dist/semantic.css. This causes the range slider to not fill the range between the two buttons as the width is fixed to 0.

**Comment by lubber-de** [comment]
The range.css is not used anymore. The component was renamed to slider.css in 2.7.0, thus there is a difference in semantic.css (because it includes slider.css, but not range.css anymore)
However thanks for pointing out those legacy files are still available inside the dist folder. I will prepare a PR to remove them.

**Comment by eazrael** [comment]
Good to know. Thank you :-)
