### ISSUE TITLE
Labels dont have same vertical size as buttons, inputs, selects...

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#1792]
One thing that I really link on FUI is that you can trust in the size (medium, big, large...) and apply it to buttons, inputs, selects (dropdown)... and they will look identical in vertical size and in many case they share the same padding, margin... However with labels, that is not the case. For example: the `medium` size is the default for buttons, inputs... and their vertical height is the same and if I place a `<div class="ui label">`  at the side of those elements, the vertical size of the label will be much much smaller. Ok, no big deal, I tried applying the `big` and `large` class to the label, however there is no good fit (not even close), the `large` is noticeably smaller and the `big` is noticeacly bigger.

So I cant even find a defined size for the label that matches the same size of a `medium` button, input, dropdown... Or am I doing something wrong?

Also notice that the margin is different, the label is not with equal distance from the other buttons itself.

![image](https://user-images.githubusercontent.com/8988923/102136995-eb32d580-3e38-11eb-92aa-0a680e1188c8.png)

![image](https://user-images.githubusercontent.com/8988923/102137053-ff76d280-3e38-11eb-8254-f6995c0f9755.png)

**Comment by lubber-de** [comment]
That's intention and should not be considered a bug.
Labels are meant to be in flow with a Textline, that's why their equal size name is overall smaller than buttons or inputs, and to visually differ between them.

To get a better idea of why that matters, look at [Horizontal labels](https://fomantic-ui.com/elements/label.html#horizontal), [Pointing labels](https://fomantic-ui.com/elements/label.html#pointing) , [Floating Labels](https://fomantic-ui.com/elements/label.html#floating) or Labels inside Inputs for example  in the Multiple Selection Dropdown

However, there exists adjustmensts already to match the same size/margin/padding when used in [labeled input](https://fomantic-ui.com/elements/input.html#labeled) or [labeled button](https://fomantic-ui.com/elements/button.html#labeled)

Of course you can adjust the values for padding/margin in `label.less` according to your needs, but we should not change the default theme

**Comment by batata004** [comment]
Thank you and I totally agree with you. However, sometimes I just want some label alongside buttons to display some information (like in the print above) and the `labeled button` are not a great idea because they allow user to interact with it (hovering the mouse, changes its color, the default cursor is `pointer`, clicking down the mouse also change the color of the button...) and the user may think that the button is broken if nothing happens when they click the button (and nothing should happen since it's supposed to be a label and not a button).

I know I can override most settings in custom css files but in many projects I import FUI from CDN so I need to add the changes inline to the elements or override styles on a separated stylecheet.

Anyway, if there is no way I can at least style the label to the same size as button (even using a different name) I will stick with a `<div style="height:30px; border-radius:5px; border:1px solid grey; color:grey; padding:7px;">My Label</div>`  - it's ugly but gets the job done :)

**Comment by lubber-de** [comment]
Instead of inline styling (each label) for your usecase, i suggest to override it at a central place , if you want  it for all your labels. From what i see, only the padding for a `large label` needs adjustments, so it will 
look just like a button in size.

```
.ui.large.label {
 padding: 0.78571429em 1.5em; 
}
```
See https://jsfiddle.net/lubber/bze3r1uL/11/
![image](https://user-images.githubusercontent.com/18379884/102712311-78a27980-42c0-11eb-871a-a8bbb944d6a1.png)
