### ISSUE TITLE
How to make Fomantic work with jquery slim?

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#1897]
I know FUI is jQuery dependant and there is no easy way to run FUI without jQuery. I get it :) But I was trying to use jquery slim version with FUI and had lots of problems.

Is there some build `flag` that I can set on gulp so FUI gets built with only the jquery slim code, without ajax/effects which are jquery dependant?

**Comment by lubber-de** [comment]
No there isn't and it would be an easy task anyway, because lots of overall used functions are removed form the slim version. Especially `$.fn.extend` and `$.each` which is used in every module at several places.
You might have to use a ployfill for those missing methods instead.

Other missing (animation) methods like `.fade` could be fetched for a check of existance inside the js modules

**Comment by batata004** [comment]
@lubber-de thank you for clarifyng this. I will not waste more time trying to use slim version!

**Comment by lubber-de** [comment]
🤔 I just looked at 3.5 slim and i was wrong. `each` and `extend` seem to be included... at least the animations are removed, i look into it again
https://code.jquery.com/jquery-3.5.0.slim.js

**Comment by lubber-de** [comment]
Ok, basically everything ajax or animation (also opening modals...) related does not work, but everything else should work
https://jsfiddle.net/lubber/ofgjrqda/5/

**Comment by batata004** [comment]
Awesome news! For some stupid reason I was still using the latest 1 version for better browser compatibility but I dont need it anymore. I can afford jquery 3 version! Back to work, now I will make it work! Thanks a lot for your investigation!
