### ISSUE TITLE
[popup] exists Behavior returns always false

### ISSUE THREAD

**Issue by maidzen** [fomantic/Fomantic-UI#1926]
if you create a popup

$('.element').popup()  and check if its created with the exists behavior  $('.element').popup('exists) 
it returns always false

Example:
https://jsfiddle.net/w0qe7tb4/1/

Version 2.8.4

**Comment by lubber-de** [comment]
This isn't a bug.
Your jsfiddle declares the popup to be shown on hover. Thus the `exists` behavior only returns true when the popup is still there.

I adjusted your jsfiddle for a better understanding. 
The first button shows the popup. The second button checks for existance on click (instead of a one time timeout)

Whenever a popup is shown, the second button returns true as expected.
If the popup is not shown, if will return false (as expected)

https://jsfiddle.net/lubber/zvymjsc8/4/

![popupexists](https://user-images.githubusercontent.com/18379884/112463975-311a0680-8d63-11eb-902d-d2dc9556277e.gif)

**Comment by maidzen** [comment]
What is the difference between "is visible" Behaivor and "exists"?
is there a way to check if element is an Initilized popup?

**Comment by lubber-de** [comment]
`exists` checks for an existing dom node for the popup
`is visible` also checks if an existing popup domnode has the `visible class`

By default the popup will be removed from the DOM when hidden. (inline=false)
When you set `inline` to true, the popup will not be removed when hidden, so `exists` will still return true, while `is visible` will return false

**Comment by maidzen** [comment]
i get it the difference is only clear with inline popups, thanks for the explanation!
