### ISSUE TITLE
[scope] Numeric input increase/decrease icons are not working in the latest version of Firefox

### ISSUE THREAD

**Issue by ldembowski** [fomantic/Fomantic-UI#1956]
# Bug Report
Numeric input increase/decrease icons are not workin in the latest version of Firefox, they are not available for click
![image](https://user-images.githubusercontent.com/4338117/116510330-a88c0a00-a8bc-11eb-8fa3-ba9dacca5c35.png)

## Steps to reproduce

Standard form usage

`<div class="ui form">
  <div class="field">
  <label for="number-in">Number</label> 
  <input id="number-in" type="number" min="1" max="5">
  </div>
</div>`

## Expected result
Icons should be accessible for mouse click in order to increase or decrease number

## Actual result
Icons are unclickabe

## Testcase
Stardard number input field with latest version of FF

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/4338117/116510330-a88c0a00-a8bc-11eb-8fa3-ba9dacca5c35.png)

## Version
2.8.7

**Comment by lubber-de** [comment]
This seems to be a general firefox bug, because it is related to the given right padding.
Even if you do not use fomantic, but raw html and apply a right padding to the input, the bug also occurs.

### Examples
When using `padding-right:1em;` even on raw inputs not using fomantic, firefox does not let you click on the arrow buttons
https://jsfiddle.net/lubber/oxh4e3vr/9/

Workaround: Use `padding-right:0em` on every number input 
https://jsfiddle.net/lubber/oxh4e3vr/10/

**Comment by donaggio** [comment]
I found that you can increase a little the right padding, but not too much: `padding-right: 5px`  works well for me and it is visually more appealing than `padding-right: 0`
