### ISSUE TITLE
[bug] Top arrow of dropdown not showing on `.scrolling`

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#2103]
Please take a look at https://jsfiddle.net/h57kwr8L/

Click on `Teste` and you will see the dropdown menu does not show the arrow on top of it. However, if I remove the `scrolling` class it works as expected, see example below:

https://jsfiddle.net/og16Lykm/

Or am I doing something wrong?

Thank you so much for this really nice library!

**Comment by lubber-de** [comment]
The `scrolling class` adds `overflow-y: auto` to the menu. Because of that the pointer, which is made of the `:after` pseudoclass, cannot be shown anymore because the pointer is outside of the container scope, means it is "overflowing".

I explained this [here](https://github.com/fomantic/Fomantic-UI/issues/565#issuecomment-472327377)

I am therefore marking this as a duplicate of #565

However, i am already playing with support for https://popper.js.org/ which most probably will fix many other similar issues as well.

**Comment by batata004** [comment]
Ah sorry! Thank you so much! I tried fixing this making "overflow:visible" and it works (the arrow shows up) but the scroll bars disappeard. Anyway, thnk you!
