### ISSUE TITLE
[table] Headers Not Inverting in Table

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2146]
# Bug Report
In an inverted table, headers are not inverting

## Expected result
Headers should take the colour of the inverted text (white)

## Actual result
Headers appear as black

## Testcase
https://jsfiddle.net/qtby94rv/

**Comment by jamessampford** [comment]
Ah, seems just need to give the header `inverted` - https://jsfiddle.net/cp8o10fw/ - kinda understand the logic, but think would be better if the colour were instead inherited if a parent is inverted?

**Comment by lubber-de** [comment]
The `inverted header` tells the component to use a light color, but it cannot guess what the background color is and there is no CSS specification to look back into parent nodes.
And a header inside a table could get the wrong color if it's just being inherited. Even if this would work in your use case, your suggestion to change the color for an inverted table to `inherit` will most probably break existing code where `header` is used on other situations than inside a table.

However, the color for an inverted header can be changed by the LESS Variable `@invertedColor`, so you also always customize it to your needs and rebuild FUI with your own theme where that variable is `inherit` 😉 

Closing because you found the solution already.
