### ISSUE TITLE
[Theme] Multiple Header Colours for a theme

### ISSUE THREAD

**Issue by douglasses** [fomantic/Fomantic-UI#2188]
Hi, I've got 2 questions. 

Firstly, I am attempting to create a dark theme and achieve this below. (notice the black header at the top and the white header in the segment)
![image](https://user-images.githubusercontent.com/23068277/147315014-7789751f-9772-48aa-ba7d-293c90f55e29.png)

Is there a way to have 2 different colours of headers using the same "ui header" class instead of using "inverted" or other colour class tags? The reason being if I use an "inverted" or a color class tag on the headers, the colours will have conflicts with other themes. (e.g white text against, white background). 

Secondly, why does the header.variable file does not have a default header color variable? I could only change the header color from the site.variable text color variable.

**Comment by lubber-de** [comment]
You can already add/change color names to the header, like `ui green header`. You can customize the colors centrally inside your own `themes/{yourthemename}/globals/colors.less` file

For reference look here
https://github.com/fomantic/Fomantic-UI/blob/develop/src/themes/default/globals/colors.less 

If you only want to have an extra color only for the header, still define that inside the colors.less file, but limit the colors for the header inside your `site.variables` file of your theme like this

```less
// The new color names "nameyourowncolor" and "whatevercolornameyouwant" have to be declared inside the above mentioned "colors.less" file
@variationHeaderColors: blue, green, nameyourowncolor, whatevercolornameyouwant;
```
For reference look here
https://github.com/fomantic/Fomantic-UI/blob/develop/src/themes/default/globals/variation.variables



> Secondly, why does the header.variable file does not have a default header color variable? I could only change the header color from the site.variable text color variable.

Because the default is to use the globally available textcolor. However, you are free to override this value inside your header.variables file. This way the variable will change ONLY for the header, not globally.

```less
// set this inside your {mytheme}/elements/header.variables
@textColor: #013370;
```
