### ISSUE TITLE
[calendar] calendar uses incorrect formatter for specified type

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2268]
# Bug Report
Possibly an incorrect expectation on my behalf, however, in my thinking if the calendar is set to `type: 'date'` and a formatter is provided for `date`, then that formatter should be used if multiple formatters are provided. Instead, `datetime` is provided back. The same seems to also happen with `type: 'time'`

## Expected result
The response should use the formatter match the stated type

## Actual result
The response format uses datetime formatter when multiple formatters are provided

## Testcase
https://jsfiddle.net/9oz4u8jv/1/

## Version
2.8.8

**Comment by lubber-de** [comment]
Fixed by #2324 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/1zkc0jdv/
You can now also simplyfy the formatter by using token strings instead of custom functions (which is still possible as seen in the jsfiddle above)
Your same example using such tokens here https://jsfiddle.net/lubber/1zkc0jdv/2/
