### ISSUE TITLE
[Pagination/Menu] Flex-wrap should be set for all inline-flex styles

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2345]
# Bug Report

Some selectors have `display: inline-flex;` style, but are not wrapped. See actual/expected demo.

adding `flex-wrap: wrap;` style to these selectors fixes the issue

related with https://github.com/fomantic/Fomantic-UI/issues/2157

## Expected result
https://jsfiddle.net/d3w6uqnf/

## Actual result
https://jsfiddle.net/n18kh4jg/

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/2228672/165644517-345bce33-90d3-4854-b210-4bf0a77890aa.png)

## Version
2.8.8/latest

**Comment by lubber-de** [comment]
This also needs proper styling when wrapped, so i suggest to adopt the logic from `wrapping buttons` we recently implemented by #2217

**Comment by lubber-de** [comment]
Yes, use the nightly CDN tag
https://cdn.jsdelivr.net/npm/fomantic-ui@nightly/dist/semantic.min.css
https://cdn.jsdelivr.net/npm/fomantic-ui@nightly/dist/semantic.min.js

**Comment by mvorisek** [comment]
Yes, `wrapping` class is the solution and it should be supported for any component that has `display: inline-flex;` styling.

demo https://jsfiddle.net/qatcLn73/ (of course, normally there should be no `buttons` class)

**Comment by mkrecek234** [comment]
@mvorisek From a UI perspective, menus should stack, not wrap from my understanding  if you have small mobile screens vertically- you don‘t want more than one element per line in small viewport widths. On vertical oriented mobiles all menus are stacked in common applications, otherwise it is not easy to be used. Wrapping would afaik line-break according to available size which can be on top for desktop screens. Nevertheless, for mobile it ahould stack. 

@mvorisek @lubber-de Whatvdo you think?

**Comment by lubber-de** [comment]
As i [mentioned above](https://github.com/fomantic/Fomantic-UI/issues/2345#issuecomment-1112234805), just wrapping the elements most always breaks the styling, so whenever we would support a "wrapping" class those elements would need more adjustments to also work in all existing variations. (See your own example, it does not look right:

![image](https://user-images.githubusercontent.com/18379884/213994282-e31975cc-fce2-4e59-ab09-55ee5b5e3975.png)

For the pagination menu at least the borders would need to be moved to the left instead of the right. We did something similar for List items back then in https://github.com/fomantic/Fomantic-UI/pull/353

If we would simply provide a general "wrapping" class into the FUI code, which would just add `flex-wrap: wrap`, people will start complaining about elements not looking good again (as we are not tailwind which leaves everything up to the user). That's why much more was needed to make it work for buttons in #2217.

**Comment by lubber-de** [comment]
Implemented by #2682 for menu component
