### ISSUE TITLE
[form] grouped fields make a vertical scrollbar appear when it's not required

### ISSUE THREAD

**Issue by Ikaer** [fomantic/Fomantic-UI#2369]
# Bug Report
A vertical scrollbar appears when using a grouped fields 

## Steps to reproduce

1. Create a form
2. Add a grouped fields
3. Add a field
4. Add a checkbox

## Expected result
The vertical scrollbar is not needed and should'nt be displayed

## Actual result
A vertical scrollbar is displayed

## Testcase
The KO case:
https://jsfiddle.net/nyq7x96v/

The OK case when I'm not using a grouped field just a field inside a form
https://jsfiddle.net/tfrd3h1y/

## Screenshot (if possible)
The KO case:
![image](https://user-images.githubusercontent.com/7936075/167778847-da330873-f59d-412d-b994-9f93518d8647.png)

The OK case:
![image](https://user-images.githubusercontent.com/7936075/167778799-1a04812a-97c6-487a-aa5b-d01eeeef7304.png)

## Version
2.8.8

**Comment by lubber-de** [comment]
Fixed by using `display: inline-block;` instead of `display: block;`
However, this would break the width of input fields when used inside grouped fields. Therefore i fear to do this change in the core.
So, whenever you need this, please adjust this manually
See https://jsfiddle.net/lubber/ncutb2vq/4/
