### ISSUE TITLE
[reset] `<figure>` css is not reset

### ISSUE THREAD

**Issue by grandeljay** [fomantic/Fomantic-UI#2381]
# Bug Report
The HTML [figure](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) element does not seem to be reset.

## Steps to reproduce
1. Use `figure` HTML Tag

## Expected result
The `figure` element should not have a margin.

## Actual result
the `figure` element has a margin.

## Testcase
https://jsfiddle.net/ktd5ops8/

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/45571053/172569738-e114f100-f6a6-440e-be00-1c5a7061e5d3.png)

## Version
2.8.8

**Comment by GammaGames** [comment]
Looks like default behavior: 
![image](https://user-images.githubusercontent.com/7832163/172684315-5a75336a-b498-40c6-a9ef-ae5684e97cc6.png)

More of a feature request to apply styling to the element than a bug.

**Comment by grandeljay** [comment]
> Looks like default behavior:

Yes, from my understand that is the point of a reset. To undo the default browser styles.

**Comment by GammaGames** [comment]
> # [What's In Our Reset](https://fomantic-ui.com/globals/reset.html)
> Fomantic's default theme includes the latest [Normalize CSS](http://necolas.github.io/normalize.css/) to provide a base line HTML reset. In addition, Fomantic UI requires a Box-sizing reset, to make sure that elements handle width definitions in the same way.

![image](https://user-images.githubusercontent.com/7832163/172874676-d11e5a02-e23f-48a2-b867-398d8bb36a1c.png)

If you check out Normalize CSS, you can see that they had removed the margin [in 2011](https://github.com/necolas/normalize.css/commit/df279d89b45399d942c3b35ab119fe579ae06520) but added it back again [in 2014](https://github.com/necolas/normalize.css/commit/ccbb28b123186a419abd8f8211f7431885943fd9) because all browsers had the same default margin

**Comment by lubber-de** [comment]
I think, @GammaGames got valid points, so i tag this as usage and close the issue.
