### ISSUE TITLE
[scope] flyout bug

### ISSUE THREAD

**Issue by 332lfgb6** [fomantic/Fomantic-UI#2514]
# Bug Report
The modal box can pop up, but the console will report two error

## Steps to reproduce
```html
<!-- You MUST include jQuery before Fomantic -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.0/dist/semantic.min.css">
<script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.0/dist/semantic.min.js"></script>

<body>
<button id="xxx">button</button>
</body>

<script>
  $(document).ready(function(){
    $("#xxx").click(function(event){
      $.flyout({
        autoShow: true,
        title: 'Flyout Notice',
        class: 'wide',
        closeIcon: true,
        content: 'Fomantic-UI 2.9.0 was released today!',
        actions: [{
          text: 'Awesome, thanks!',
          class: 'green',
          icon: 'save'
        }]
      });
    });
  });
</script>
```

![image](https://user-images.githubusercontent.com/51245335/196519176-2aa3a7a4-4351-4ded-b14c-b28c1e59e02d.png)

## Expected result
console will report 0 error

## Actual result
console will report two error

**Comment by lubber-de** [comment]
Flyout needs a special page layout containing a "pusher" element. If it is not available, the module will create one for you and let you know by this console message. Thus, this is intended.
See https://fomantic-ui.com/modules/flyout.html#page-structure

The second console message is a logical successor of the first. Because flyout had to create the pusher, but it also had to dynamically create a flyout (which assumed there was a pusher existing, but wasn't)

**Comment by lubber-de** [comment]
> Assuming my code looks like this, how do I configure it?
> 
> ```
> <body>
> <div class="zzz">
>   <div class="pusher">
>     <button id="xxx">kkk</button>
>   </div>
> </div>
> </body>
> ```

In that case you can change the context setting to the zzz selector
```
context: '.zzz',
```
See https://jsfiddle.net/43xcr7u8/
