### ISSUE TITLE
[modal] m2.onVisible is emit before m1.onHidden in when m1.allowMultiple is set

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2515]
# Bug Report

while looking into https://github.com/fomantic/Fomantic-UI/issues/2499 I found out:

## ✔️ Steps to reproduce `m1.allowMultiple: false` and  `m2.allowMultiple: false`

https://jsfiddle.net/kpL52wen/ (open and click "Open 2nd modal")

![image](https://user-images.githubusercontent.com/2228672/196610299-79011d85-2d63-4da2-a33b-6fd454c98d00.png)

## ❌ Steps to reproduce `m1.allowMultiple: true` and  `m2.allowMultiple: false`

https://jsfiddle.net/kpL52wen/1/ (open and click "Open 2nd modal")

![image](https://user-images.githubusercontent.com/2228672/196610774-8e23bf55-fbb9-4c74-a122-529682450797.png)

## Expected result

the previous modal "paired close event" must be fired before the new modal "paired open event"

by paired events I mean pair like onShow/onHide, onVisible/onHidden

m1.onHide must be always emit before m2.onShow

m1.onHidden must be always emit before m2.onVisible

## Actual result

m2.onVisible is emit before m1.onHidden

## Version
2.9.0

**Comment by lubber-de** [comment]
Basically the events are individla for each modal and do not depend on each other. In your jsfiddles both modals are basically working/displayed.
In your other app code you are changing the dom in onhide (instead of onhidden) and setting the opacity to 0 making the dom selector think the first modal is still visible.
i am on the road atm and have to study your code more deeply later.

**Comment by mvorisek** [comment]
closing in favor of https://github.com/fomantic/Fomantic-UI/issues/2499, I opened this before I realized it seems like exactly the same problem
