### ISSUE TITLE
Cannot press comma in multiple select dropdown with allowAddition.

### ISSUE THREAD

**Issue by dannycdannydo** [fomantic/Fomantic-UI#2517]
Setting allowAdditions to true on multiple select dropdown means whenever the comma key is pressed it triggers a selection to be made of input thus far.

## Steps to reproduce
1. Create a multiple select element with allowAdditions set to true<select multiple="" class="ui fluid search dropdown addition" id="address">
2. Attempt to type the following: "test1, test2, test3"

## Expected result
selection made of "test1,test2, test3"

## Actual result
three seperate selections "test1", "test2", test3"

## Testcase
https://jsfiddle.net/uyktoqjd/

## Version

2.9.0

**Comment by lubber-de** [comment]
This is intentional as the comma is declared as delimiter between multiple values by default.
The docs tell you about that at https://fomantic-ui.com/modules/dropdown.html#/settings
![image](https://user-images.githubusercontent.com/18379884/196787328-685b7754-2868-4598-a305-b37b2aff1232.png)

So just use a different delimiter, (for example `delimiter:'|',` and your issue is solved
