### ISSUE TITLE
[modal] onHide before onVisible is corrupting the modal state

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2528]
# Bug Report

## Steps to reproduce
1. https://jsfiddle.net/osq3mx6f/1/
2. notice the `onShow`, `onHide`, `onVisible`, `onHidden` events order in the console
3. and (hidden) corrupted modal state:
   ![image](https://user-images.githubusercontent.com/2228672/198969756-d9e238d7-c425-44be-bf1b-82e19e90b2f4.png)

this `active` class added by https://github.com/fomantic/Fomantic-UI/blob/2.9.0/src/definitions/modules/modal.js#L576 to an already hidden modal leads to corrupted state, especially with `allowMultiple` which then try to close the modal again wrongly

## Expected result

https://jsfiddle.net/osq3mx6f/2/ (the same fiddle just with `modal('hide')` fired/delayed after `onVisible`)

![image](https://user-images.githubusercontent.com/2228672/198970194-68833b75-b0cc-452d-a6ec-534ea85bff7c.png)

I would expect `$modal.transition.onComplete` (https://github.com/fomantic/Fomantic-UI/blob/2.9.0/src/definitions/modules/modal.js#L570) (and `onVisible` inside) NOT called.

## Actual result

(see 2nd and 3rd step to reproduce)

## Version
2.9.0

**Comment by lubber-de** [comment]
Mmh, in your example you force to hide the same model before it is actually visible. The onShow starts the fade in transition.
Of course, if you force to hide it while the transition for fade in is not finished, this breaks tjhe logic

I changed your jsfiddle to use onVisible instead of onShow and it then working as expected
https://jsfiddle.net/8omjgs9v/

**Comment by mvorisek** [comment]
In atk4/ui I fixed it this way:

https://github.com/atk4/ui/blob/95e659a0548e1396f7a8b4ce23f36367ad0d1b10/js/src/services/modal.service.js#L132-L134

I belive this has to be fixed officially, hide must cancel the show transition. This problem is present in other (non-modal) modules as well.

**Comment by lubber-de** [comment]
Fixed by #2676 

I played with that for a while today:
The order of the callbacks does not matter here, so the above mentioned PR still keeps the onShow, onHide, OnVisible, onHidden order if you are doing the way you did it in your jsfiddle (running onHide within onshow instead of onvisible)

So, instead, i just made sure the active class gets (also) removed after the modal is hidden which solves your core issue.

Stopping the already running animation via "stop all" inside the onhide/onshow events, would still not force the desired order as "onHide" is also checking if a possible given callback returns false and will eventually cancel the whole hide method, so we can not force the stop transition before.

So, if you really need to have the desired order (despite of the change i did now), you would have to call `.transition('stop all')` before you actually call `.modal('hide')` 

Also, it was the intention to support in between  animations by 51cf4f5b5888c290446000a2c36da2399fe41c36 and modal also supports the `queue` settings, which would not work anymore if we always stop the transition inside the modal core code.

**Comment by mvorisek** [comment]
IIRC I needed the `onComplete` callback https://github.com/fomantic/Fomantic-UI/blob/2.9.0/src/definitions/modules/modal.js#L570 not called, but even /wo the fix and no `$modal.transition('stop all')` our tests are passing... I will reopen in the future with better repro if needed...
