### ISSUE TITLE
This issue is follow up of the issue https://github.com/fomantic/Fomantic-UI/issues/2563

### ISSUE THREAD

**Issue by ashishemptyops** [fomantic/Fomantic-UI#2570]
# Bug Report
Thanks for providing the details in the last issue. I acknowledge that we had some tweaks around the slider behavior but it is working for a long time right now on many different sites. I am providing the link to one such site below where it is working. 
https://dazzlediamondslondon.co.uk/product-category/eo_diamond_shape_cat/?EO_WBC=1&BEGIN=eo_diamond_shape_cat&STEP=1&FIRST&SECOND
Let me know if I should open a new bug then I will do so.

## Steps to reproduce
1. Please go to this link "https://thediamondart.com/product-category/engagement-ring/?EO_WBC=1&BEGIN=engagement-ring&STEP=1&FIRST&SECOND"
2. Open the console.
3. Lock at this error: Uncaught TypeError: Cannot read properties of undefined (reading 'range') -> "return $module.hasClass(settings.className.range);"

## Expected result
Range Slider Work

## Actual result
The range Slider is not working.

## Version
2.8.6

**Comment by jamessampford** [comment]
I'd recreate it as a Jsfiddle as previously advised...

**Comment by lubber-de** [comment]
@ashishemptyops As [i told you in the previous issue](https://github.com/fomantic/Fomantic-UI/issues/2563#issuecomment-1320901211) and also @jamessampford suggested:
Please create a simple reproducable jsfiddle. We don't have the time to debug your big website having tons of additional and obfuscated/minimized code. Thanks. 

Please do *not* open another issue for the *same reason* again to keep the issue list clean. If needed, comment on the old issue. 
Thanks.

Closing, because of being  a duplicate and until a jsfiddle is provided,so we can be sure it's a FUI bug in the core.
