### ISSUE TITLE
[table] sortable tables

### ISSUE THREAD

**Issue by hakeem86** [fomantic/Fomantic-UI#259]
Hi,

Couldn't this table sort library be merged into fomantic-ui, just like how mdehoog's calendar was?

https://semantic-ui.com/javascript/library/tablesort.js

**Comment by hammy2899** [comment]
The calendar library was merged because it was made for SUI as a plugin and was originally a PR. This table sorting library is a jQuery library and wasn't built specifically for SUI so the chances of this being merged into the FUI code base is very unlikely.

Maybe in the future table sorting could be added natively.

**Comment by crewow** [comment]
please add table sort
