### ISSUE TITLE
[DropDown] "set selected" not working as expected

### ISSUE THREAD

**Issue by YuriFeigin** [fomantic/Fomantic-UI#2646]
# Bug Report
1. If I'm using "set selected" on dropdown builded (DOM) in JS with "multiple" option before attaching to the page, the values that was selected disappear ([reproduce](https://jsfiddle.net/mb1rghk3/12/))
2. If  I'm attaching to the page and then calling "set selected", it's working as expected  ([reproduce](https://jsfiddle.net/mb1rghk3/13/))
3. If  I'm removing "multiple" option, it's working as expected (even before attaching to the page) ([reproduce](https://jsfiddle.net/mb1rghk3/16/))

**Comment by lubber-de** [comment]
Look at the console. You will see a Message telling you, that the transition module (which fades in the value labels) cannot animate the labels anymorem because the element is not attached to the DOM anymore.

At the time you are calling "set selected" an animation transition starts to make the label "s2" appear inside of the dropdown.
But this takes longer than your immediatly reattach of the element to the "main" element. So, the s2 labels cannot be found anymore, thus wont be displayed.

To fix this, you have some options:
- call the "set selected" or initiate the whole dropdown _after_ you have reattached the node to main (as you already tried)
- Dont use label transitions. I prepared #2647 for this. See your adjusted example here https://jsfiddle.net/lubber/tzdwkre2/7/ , which now works

In addition: Your jsfiddle has a slight mistake: You are trying to instantiate a dropdown via `.ui.dropdown` selector at the time when the dropdown is not attached to the DOM, i changed that in the adjusted jsfiddle to "this.select_div" as well

**Comment by YuriFeigin** [comment]
@lubber-de Thanks a lot for the help, waiting for next version.
