### ISSUE TITLE
Dropdown closing behind other form fields

### ISSUE THREAD

**Issue by jeffmcfly** [fomantic/Fomantic-UI#2663]
# Bug Report
When dropdown field closes, it passes behind other form fields.

## Steps to reproduce
1. Create a form with a dropdown field
2. Place other fields below
3. Set long transition duration to see effect

NB. Using "slide" as "hideMethod" seems to resolve the issue : 

`transition: {
      showMethod   : 'slide down',
      showDuration : 200,
      hideMethod   : 'slide',
      hideDuration : 5000,
  }` 

## Expected result
Dropdown closing before other elements

## Actual result
Dropdown closing behind other elements

## Testcase
https://jsfiddle.net/1w0vz9tL/1/

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/94075859/213015825-ddf78dae-b21d-4383-81fd-2cb027f6e730.png)

## Version
2.9.1

**Comment by krpatel5657** [comment]
We are a group of students from CMU and we'd like to work on this issue!

**Comment by krpatel5657** [comment]
Hello! Upon changing a line in src/modules/dropdown.js to have the auto dropdown transition default to "slide" instead of "slide down," I get the following successful result:
![drop-down-working](https://user-images.githubusercontent.com/52473367/236687366-b9af03bd-5209-4253-8aab-6cf327a09cdc.gif)

This change also fixes an issue with the upwards direction of dropdown menus. Here is the original without this change:
![drop-up-notworking](https://user-images.githubusercontent.com/52473367/236687379-0ad6bf35-bfaa-40c6-a704-949847b14f52.gif)
Here is the upwards dropdown with the change:
![drop-down-working](https://user-images.githubusercontent.com/52473367/236687390-60edaff9-327f-4d30-8b85-aa3f401858c4.gif)

The line changed was within the transition property under the get method in dropdown.js, from:
`transition: function ($subMenu) {
                        return settings.transition === 'auto'
                            ? (module.is.upward($subMenu) ? 'slide up' : 'slide down')
                            : settings.transition;
                    },`
to:
`transition: function ($subMenu) {
                        return settings.transition === 'auto'
                            ? (module.is.upward($subMenu) ? 'slide up' : 'slide')
                            : settings.transition;
                    },`

Please let me know if this is considered an acceptable fix!

**Comment by lubber-de** [comment]
Fixed by #2818 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/Ld624p5m/
