### ISSUE TITLE
[form] Something in form prompt handling changed to asynchronous

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2796]
# Bug Report

After v2.9.2 some code allowing race condition was introduced.

With https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.2/dist/semantic.js there is no problem. With https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.3-beta.35/dist/semantic.js the problem is present.

This is important as before AJAX/submit, prompts are removed but AJAX response can add them back quickly.

## Steps to reproduce
1. open https://jsfiddle.net/mL3ko1st/1/
2. click "Save"
3. notice prompt displayed with text: "some error action 45"
4. click "Save" again, notice the prompt is gone

## Expected result

prompt must stay as in v2.9.2

## Version

\>2.9.2 \<2.9.3, ie. develop between these releases

**Comment by mvorisek** [comment]
https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.3-beta.16/dist/semantic.js is still working as expected, the problem is present since: https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.3-beta.17/dist/semantic.js

Looking at the commit history, I would say the problem is in https://github.com/fomantic/Fomantic-UI/commit/5e5da5da032212ab718ce32bff72de69b64d6dec

**Comment by lubber-de** [comment]
Fixed by #2800 

The root cause is that you are adding the prompt too quickly. If the timeout would have been set to something > 200 (transition module default) then the issue does not happen (of course this isnt the solution ;) )

The reason it was "working" before is that the mentioned PR supported native input validation. 
For this to work, all existing input fields are checked (not only the only that are provided as field rules to the form).
Even if the field in your example is not required , it will checked for a possible invalidation nevertheless and  if valid, a possible existing prompt gets removed. Thats the logic ever since (for fields provided via rules only)

As you did not define any manual validation rules, the field is valid and on validation via submit/blur an existing prompt gets removed. Now, you are adding the prompt again (which is fine), but too fast so it tries to add the prompt while it is animating.

See your adjusted jsfiddle here https://jsfiddle.net/lubber/gvhcaryf/

**Comment by mvorisek** [comment]
> For this to work, all existing input fields are checked

So the problem was present even before, but only if the input was validated, ie. not in some cases.

Thank you for fixing this now.
