### ISSUE TITLE
[Icons] Update to Font Awesome 6.4.0?

### ISSUE THREAD

**Issue by KiddoV** [fomantic/Fomantic-UI#2845]
# Feature Request
We should update icons to the latest Font Awesome 6.4.0 icons.

https://fontawesome.com/versions

FUI current version v5.15.4 | ~1608 free icons.
Latest version v6.4.0 | ~2020 free icons.

So ~412 new icons.

I would like to make an PR on this, but not sure where to start. If you guys can give some instruction, I think I can do this.

**Comment by jamessampford** [comment]
See #2228

Probably better for icons to not be bundled in apart from core icons (keeps FUI lighter too) - though even better if can optionally provide an icon class path to use with other icon sets (eg. for the search specify an icon to use instead of the magnifying glass, or, specify own filter icon to use, etc)

You can use any icons you want by including them via CSS and using the syntax

I have previously done this and use `.icon` as per usual, but also the FA usage convention using only the FA icons needed to optimise pagespeed

**Comment by lubber-de** [comment]
@KiddoV  You can always create the necessary LESS icon mixing for the FA set of your choice by using our https://github.com/fomantic/create-fomantic-icons tool and build FUI yourself
Otherwise , what james said and linked to the other issue and the comments there.
