### ISSUE TITLE
[Text] Implement color text element

### ISSUE THREAD

**Issue by lubber-de** [fomantic/Fomantic-UI#289]
# Feature Request

## Description
Implement an element `ui {color} text`to style simple text with colors similar to `header` but without all the extra variations (exception perhaps: `disabled`). This is a high demanded feature since ages and should be simple to implement.

## Example
```html
<div class="ui red text">
    <span class="ui violet text">I am ultra violet</span>
    <p>i stay red</p>
</div>
<div class="ui red inverted segment">
    <p class="ui green text">
        Hulk gets angry
    </p>
    <p>
        Phew, being Bruce Banner again
    </p>
</div>
```

If the FUI Admins agree,, i am going to implement this while doing the central color definition PR. #261 

## Relates to
 https://github.com/Semantic-Org/Semantic-UI/issues/1885
https://github.com/Semantic-Org/Semantic-UI/issues/2654
https://github.com/Semantic-Org/Semantic-UI/issues/5564

**Comment by lubber-de** [comment]
@YamiOdymel As mentioned in my description , if you take a sneak peak to https://github.com/fomantic/Fomantic-UI/pull/261 your suggestion will be entirely implemented soon by defining your own color naming logic. ☺

**Comment by hammy2899** [comment]
We might want to talk about this because I agree with @YamiOdymel about using `span` tags to define where to apply the color. Having the ability to add the color classes to all elements will add a whole other level of complexity to managing overriding styles.

As @lubber-de has already said the new color system implemented in https://github.com/fomantic/Fomantic-UI/pull/261 will allow you to define your own colors so it shouldn't be a problem because it will make the defined colors universal.

**Comment by lubber-de** [comment]
I only had a very simple implementation in mind. I would also agree to the "span only":

```css
span.ui.red.text {
  color: #ff0000;
}

span.ui.disabled.text {
   opacity: .45;
}
```
