### ISSUE TITLE
"required" attribute is not preserved when initializing an existing <select> as a dropdown

### ISSUE THREAD

**Issue by DanielSwain** [fomantic/Fomantic-UI#2940]
# Bug Report
When a `<select required="">` in the html is initialized with `.dropdown()`, the `required=""` is no longer present after initialization as a `ui dropdown`.  I want to style the `<div class="ui dropdown">` that wraps the `<select>` after initialization using the css `has()` selector in order to indicate that the dropdown is required (for instance, like this:  `.ui.dropdown:has(select[required]) {border-left: 3px lightblue;}`).  However, I cannot do that because the `required` attribute is being removed from the `<select>`.  Also, the field is not correct as far as `<form>` validation because it isn't being validated on the client side as **required** since the `required` attribute is missing.

## Steps to reproduce
1. Include the following in html (or just see fiddle under Test Case below):
```
<select required="" name="anything">
    <option value="">---</option>
    <option value="1">1st choice</option>
    <option value="2">2nd choice</option>
</select>
<script type="text/javascript">
    $(() => {$('select').dropdown()}
</script>
```
2. In the browser developer tools, set a breakpoint on the above script.
3. When the breakpoint is reached, see that the `<select>` still has the `required` attribute set.
4. After the above script executes, view the `<select>` in the developer tools and see that the `required` attribute has been removed.

## Expected result
The `required` attribute (and all other attributes for that matter) on the `<select>` should be preserved and be present after initialization by `.dropdown()`.

## Actual result
The `required` attribute has been removed.

## Test Case
[https://jsfiddle.net/zo3da4f8/2/](https://jsfiddle.net/zo3da4f8/2/)

## Screenshot (relevant parts from the above fiddle)
![image](https://github.com/fomantic/Fomantic-UI/assets/7819909/f60e4739-acdd-4988-b4e2-5c0a734b5652)

## Version
2.9.3

**Comment by lubber-de** [comment]
This was intentionally invented by #920 as the select tag is converted into a div dropdown and the select remains hidden which prevented form submission

**Comment by DanielSwain** [comment]
@lubber-de Thanks for your quick reply.  I've used Semantic/Fomantic for years and have been very pleased with this library as well as with the continued progress under Fomantic.  Just a question/comment (and I realize this has probably been explained somewhere before), but I can't determine the reasoning for when a `<select>` is included within a `.ui.dropdown` declaration and when it isn't, and I see nothing in the docs regarding this matter.  The following screenshot shows [this portion of the docs](https://fomantic-ui.com/modules/dropdown.html#search-selection) where there are two declarations with the only visible difference appearing to be the width of the elements.  Number 1 below is declared **without** a `<select>` but number 2 **has** a `<select>`.

![image](https://github.com/fomantic/Fomantic-UI/assets/7819909/28569e48-5632-4a24-8f9c-19bf42431348)

If a `.ui.dropdown` can be declared without a `<select>` element as in number 1 above or as [shown in the docs here](https://fomantic-ui.com/modules/dropdown.html#initializing-existing-html), then why would a `<select>` ever be needed as part of a `.ui.dropdown` declaration?  Our forms are rendered server-side, and while we could change the template that renders a selection-type element, it's just quicker to apply `.dropdown()` to the standard `<select>` elements that are rendered.  So my question:  As part of the initialization/transformation of a `<select>` into a `.ui.dropdown`, could the `<select>` just be removed from the DOM and any attributes (and I'm really only concerned with the `required` attribute) be transferred to the `<div class="ui selection dropdown" ...>` and then an `<input>` with the name of the `<select>` be inserted into the DOM?  This would then accomplish making the html for the `.ui.dropdown` always look like number 1 above.  Maybe there would be security concerns with this approach, or perhaps there is some other reason this wouldn't be a good solution, but I just wanted to ask the question.  Since there is currently no `<input>` created as part of the `.dropdown()` initialization of a `<select>` element, it seems like, under the hood, any time a choice is made via `.ui.dropdown`, it is then being synced back to the underlying `<select>`, so it seems like that synchronizing could be eliminated if the `.ui.dropdown` was always had the same structure.

**Comment by lubber-de** [comment]
The only reason a `select` is found inside a dropdown component is an automatic conversion when instantiated directly on a `select` tag.
It's indeed only "somewhat" mentioned here https://fomantic-ui.com/modules/dropdown.html#selection
![image](https://github.com/fomantic/Fomantic-UI/assets/18379884/79344ac2-1b9e-4099-8bc5-5bc26ef5e88d)

### Why the conversion?
Reason for the conversion at all are the dropdown features which are otherwise not possible directly on select tag and a native select tag unfortunately cannot be completely styled the way we want it (at least the menu is very limited) (we will most probably support native select styling in a future FUI version in a limited way)
However, to store selected data, an "official" form element needs to be privided. For that reason either a hidden input field is needed, or, in case of a select conversion, the original select tag is used.

### Why does the mentioned demo use a select tag and an input?
The first dropdown of the demo uses additional HTML elements for each entry (the flags). This is not possible using a standard select tag conversion as a `option` tag cannot include html (at least existing html won't be rendered). Thats why a manual `div` dropdown component is used here which allowes all of the possible FUI dropdown features.

The second dropdown only contains text. Thats's why a simple `select` conversion was used here.

**Comment by lubber-de** [comment]
Replacing the original select by an input automatically could have some drawbacks
- it might break code as people can still access the original select and probably rely on that and a select hat other properties than an input
- the dropdown component would need som significant rewrite
- ... at least it should be thought about wisely for possible other kind of issues it might has

btw:
The current logic for the "required" attribute (if existing to the selec tag) is to automatically set "forceSelection" to true
You could also play with it by adding "required" as classname to the original select (it will be adopted to the div conversion and recognized in case you use FUIs form validation.

**Comment by DanielSwain** [comment]
Thanks for all of the feedback @lubber-de.  I'll close this out then and watch for future improvements.  Glad to know Fomantic UI is still very active.
