### ISSUE TITLE
[npx gulp build] Reference Error

### ISSUE THREAD

**Issue by ghabriel25** [fomantic/Fomantic-UI#3056]
# Bug Report
I'm trying to install fomantic ui with npm just like [the documentation](https://fomantic-ui.com/introduction/getting-started.html#installing-via-npm) but unfortunately get this when I try run `npx gulp build`

## Steps to reproduce
1. Installing via NPM `npm install fomantic-ui` in my project (fresh laravel project)
2. `cd node_modules/fomantic-ui` then `npx gulp install` (folder: resources/semantic/)
3. Here is my `package.json`
![image](https://github.com/fomantic/Fomantic-UI/assets/151924216/1a3e705b-b74e-487e-9989-414a6f36c3da)

5. `cd resources/semantic/` then run `npx gulp build`

## Expected result
Run `npx gulp build` without error

## Actual result
An error occured with label **ReferenceError: require is not defined in ES module scope, you can use import instead**

## Screenshot (if possible)
![image](https://github.com/fomantic/Fomantic-UI/assets/151924216/f51f575a-febf-48aa-9bcd-4a6531b8492c)

## Version
2.9.3

**Comment by zwcloud** [comment]
won't fix? Why? It stops me from building fomantic-ui. How can I customize fomantic-ui?

**Comment by lubber-de** [comment]
You seem to have changed your gulpfile to use es6 syntax, which won't work with the current csj gulpfile syntax of fui

Running `npx gulp build` inside fomantic folder using default gulpfile works fine.

We would need to rewrite all install scripts to es6 modules and also fork all used gulp plugins and rewrite them to es6 as well.

Instead of doing all that, we already considered rewriting the whole build system and going away from gulp. But this is still in progress and takes time.

**Comment by ghabriel25** [comment]
Hi @zwcloud @lubber-de Sorry that I close this without any information. What I've done as workaround was to remove `"type": "module"` before running `npx gulp build`. After all done, add it again.
