### ISSUE TITLE
"Awesome Semantic UI": discussion

### ISSUE THREAD

**Issue by douglasg14b** [fomantic/Fomantic-UI#421]
Hi All. I've acquired the [awesome-semantic-ui](https://github.com/douglasg14b/awesome-semantic-ui) repo and am updating it to deprecate deprecated libraries and add the many new and active ones.

I need your help! Point me towards active projects, sites, themes, tools, or even just reference material. Or make a pull request and I'll get it added in.

**Comment by douglasg14b** [comment]
@levithomason 

I see there are three Semantic-React repositorties:

* https://github.com/Semantic-Org/Semantic-UI-React
* https://github.com/stardust-ui/react-old (moved to the next repo?)
* https://github.com/stardust-ui/react

The `Semantic-UI-React` has seen recent activity as has `stardust-ui/react`. Are these two separate entities at this point or are they one and the same? Or have they forked and are going down different directions? If the later, how would you describe each in a sentence for the "awesome" list?

**Comment by hammy2899** [comment]
@douglasg14b They are different frameworks. Semantic-UI-React is the react repo for SUI and is still actively maintained. The stardust repo is the new agnostic framework as discussed in #319 which @levithomason and his team are working on. I wouldn't add it to the list yet since it is still in an early prototyping stage.

**Comment by douglasg14b** [comment]
Will do! Thanks.

**Comment by prudho** [comment]
I just released a Brunch skeleton powered by Fomantic UI:
- https://github.com/prudho/brunchmantic
