### ISSUE TITLE
Margin-right on icons inside breadcrumb

### ISSUE THREAD

**Issue by hakeem86** [fomantic/Fomantic-UI#423]
# Bug Report

If you add a icon inside breadcrumb a 0.25 rem margin is added to the right. 
There is no margin if you do a section, and don't think icon should have it.. 

## Testcase
https://jsfiddle.net/g49ucojv/

## Screenshot (when possible)
![alt text](https://i.ibb.co/wQ2cc9N/Untitled.png)

## Version
2.7.1

**Comment by hammy2899** [comment]
You need to add `fitted` to the icon. 
https://fomantic-ui.com/elements/icon.html#fitted
https://jsfiddle.net/x4cy7pzj/

This is not a bug since a user can still put text after an icon in the breadcrumb like the following 
![image](https://user-images.githubusercontent.com/11588822/51732547-91736780-2076-11e9-8401-de7476df3abd.png)
