### ISSUE TITLE
[Popup] extra tooltop appears underneath on CSS only

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#442]
# Bug Report

## Steps to reproduce
1. Create a new tooltip (CSS only) https://fomantic-ui.com/modules/popup.html#tooltip
2. Hover mouse over in FireFox and wait 1-2 seconds

## Expected result
Tooltip should show as normal

## Actual result
Tooltip shows and then it appears an extra tooltip opens underneath it after a few seconds

## Testcase
https://jsfiddle.net/9850tpo4/

## Screenshot
![image](https://user-images.githubusercontent.com/11588822/51902057-044f4c00-23b1-11e9-9da9-09a92b98c82c.png)

## Version
2.7.1

**Comment by lubber-de** [comment]
I cannot reproduce this anymore on Firefox 77 and FUI 2.8.6 and also not using the old 2.7.1

**Comment by ko2in** [comment]
I can still reproduce on Firefox 77.0.1 (64-bit) and Firefox Developer Edition 78.0b9 (64-bit) on Ubuntu 18.04.4 LTS.

It only happens with `left center` and `right center` direction. The other directions look fine. Here's fiddle (https://jsfiddle.net/bg7j2Lzo/)

**Comment by lubber-de** [comment]
mmh, ok, seems to be related to posix, because it does not happen on windows+FF, but i could reproduce on mac+FF using browserstack ...:(

**Comment by ko2in** [comment]
As far as I've tested, it looks like Firefox bug. It can only reproduce with 14px font size at zoom level between 100% and 120%. The following statement specifies in `site.css` relates to this bug.
```
html {
  font-size: 14px;
}
```
Without this, it doesn't happen, but the font size in the whole UI will be effected. Here's fiddle (https://jsfiddle.net/y78ek21t/).

I've also reproduced the tooltip with just only CSS and HTML and got the same result (https://jsfiddle.net/yo9aecj5/). It's also OK if the font size is not 14px (https://jsfiddle.net/yo9aecj5/1/).

I guess the bug is relying within the scale function in transform property. This bug doesn't occur when the scale function has value like '1.0001' instead of '1'. Here's fiddle (https://jsfiddle.net/w4p5gjra/1/).

Maybe, this should report to [bugzilla](https://www.bugzilla.org/).

**Comment by lubber-de** [comment]
@ko2in Thanks lot for investigation and finding the reason! 👍 
So, a fix for FUI would be
```css
  [data-tooltip][data-position="left center"]:hover:after,
  [data-tooltip][data-position="right center"]:hover:after {
    -moz-transform: translateY(-50%) scale(1.0001) !important;
  }
```

However, this still moves the text inside of the popup one pixel to the bottom after 1-2 seconds (as before, but now the popup border is not affected anymore which makes it "less visible")
See https://jsfiddle.net/c3qorphu/

Thanks for investigating, i prepared PR #1537 for that.

**Comment by lubber-de** [comment]
Wait... Just recognized:
@ColinFrick already prepared a much better fix using `-moz-transform-style: preserve-3d;` in his repo but never prepared a PR for this...
https://github.com/ColinFrick/Fomantic-UI/commit/38f46ce20a46854e2a500060b05ac7eb7fd3aee8

It seems to work much better than the scaling hack approach. See
https://jsfiddle.net/c3qorphu/1/

**Comment by lubber-de** [comment]
mmh, after retesting it again the preserve-3d solution was not always working (even when using the same jsfiddle!)
So we should stick with the scale solution fix

**Comment by ko2in** [comment]
Yes. It doesn't work for me. If we set the same value '1.0001' for default, it'll be fine. See: https://jsfiddle.net/ga640dzc/
