### ISSUE TITLE
[Popup] Popup getting cropped within scrolling modal

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#471]
# Bug Report
When a scrolling modal contains popup element, it crops the overflow area of popup element and thus cannot be displayed properly. Only parts of popup within the scrolling container are appearing. It's because of `overflow` property from the container.

## Steps to reproduce
1. Create a modal which can scroll internally
2. Add the popup element in the modal and places near the edges of container
3. Put the mouse over on the popup element

## Expected result
The popup should display as it should be.

## Actual result
The popup displays partially. Some area of popup are cropped by the container.

## Testcase
You can test with this fiddle (https://jsfiddle.net/xu0yh372/). The default modal without scrollbar doesn't have this problem.

## Screenshot

![tooltip-in-scroll-modal](https://user-images.githubusercontent.com/930315/52511362-fa89dc00-2c2d-11e9-9d0b-647ba7d556aa.png)

## Version
2.7.2

There is also similar issue with dropdown component I reported [here](https://github.com/fomantic/Fomantic-UI/issues/448). Technically, they're the same and leads to the huge change to fix this problem.

In my opinion, FUI should be reconsidered about the HTML structure of some component within DOM, especially with dropdown and popup which needs to be appeared at the highest level than other components. Some of those should be direct child of `body` rather than the specific container.

**Comment by apple-idn** [comment]
popup includes calendar

**Comment by lubber-de** [comment]
Same reason as in #565 :
- The popup is generated relative to its releated item and is part of the DOM of that container.
- The Container itself has overflow-x/y set by the `scrolling content` class
- Because of this the popup behaves just like a usual element within the container and gets hidden when is reaches the edge of a container

Without a general rewrite how dynamic elements like popup or dropdown menu appear on screen, i don't think this is easily solvable

**Comment by lubber-de** [comment]
Closing as tooltip is a css only feature which cannot be fixed for the above mentioned reasons (trapped insite parent overflowing container and tooltip is created via pseudo elements.

For popup (js component) as well as for calender the `context` settings can be used and set to body to fix this.
The calendar margin is also fixed since some FUI versions
