### ISSUE TITLE
Feature: Module/helper to auto-generate Table of Contents

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#475]
# Feature Request

## Description

ToC (table of contents) like the ones in [FUI/SUI docs site](https://fomantic-ui.com/introduction/new.html) are very helpful for end-users to navigate contents.

However, though it is very common feature, it needs a lot of work to implement.
It requires deep understanding of `sticky`, `menu` and `dropdown` modules, and lots of JavaScript codings to traverse DOMs and generate ToC and anchors.

It would be great if FUI/SUI support high-level module (combination of low-level component `sticky` and `dropdown`) or helper functions to generate ToC automatically.

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/127635/52548364-a68b1d00-2e10-11e9-9b45-d06142548f78.png)

**Comment by hammy2899** [comment]
I think this would be too much of an abstraction since you can create this with the existing components like you said. Maybe we can take another look at this in the future but it would require heavy dependencies on other components and I want to keep such changes to a minimum to eliminate any complexity.
