### ISSUE TITLE
Sub headers in inverted segments are unreadable (black on black)

### ISSUE THREAD

**Issue by ocharles** [fomantic/Fomantic-UI#486]
# Bug Report

## Steps to reproduce

See attached jsfiddle.

## Expected result

The sub header is readable (probably white, the same as the main header text).

## Actual result

The sub header is unreadable as it's the same colour as the background.

## Testcase

https://jsfiddle.net/thm9zvx2/

## Screenshot (when possible)

![fomantic ui sandbox jsfiddle](https://user-images.githubusercontent.com/20878/52711488-d6a9fb80-2f89-11e9-8d2c-b1e39aa65e91.png)

This is slightly out of date, please see the JSFiddle.

**Comment by lubber-de** [comment]
It works using `inverted sub header`. See https://jsfiddle.net/d3y0apjs/
I admit `header` is especially covered when used inside a `inverted segment` and `sub header` is not. 
I remember we decided against supporting all kinds of possible content inside a inverted segment to change the color automatically on component basis (because there is basically always an `inverted` variant for each component), so i am not 100% sure if we should support at least `sub header` automatically... although an appropriate PR is done quickly
```css
.ui.inverted.segment .sub.header {
    color: #ffffff;
}
```
@hammy2899 @prudho @ColinFrick  Your thoughts?

**Comment by hammy2899** [comment]
@lubber-de I think in this case it is inconsistent so it should be changed.

A header will be inverted if the parent component is also inverted but the sub header won't yet if the header is inverted itself the sub header will be.

**Comment by lubber-de** [comment]
Fixed by #488 
See https://jsfiddle.net/yo2fpcL1/

**Comment by ocharles** [comment]
Wow, I'm not used to this prompt response :smile:
