### ISSUE TITLE
[Calendar] should provide leading zero

### ISSUE THREAD

**Issue by MarcelMpunkt** [fomantic/Fomantic-UI#508]
# Feature Request

## Description
in Forms the date is outputed in this format 6.5.1999
it should be possible to be like 06.05.1999 -> with leading zeros

## Workaround
 put certain if-statements in the formatter property
 formatter: {
                        date: function (date, settings) {
                            if (!date) return '';
                            var day = date.getDate();
                            **if (day.toString().length < 2) {
                                day = "0" + day
                            }**
                            var month = date.getMonth() + 1;
                            **if (month.toString().length < 2) {
                                month = "0" + month
                            }**
                            var year = date.getFullYear();
                            return day + '.' + month + '.' + year;
                        }
                    },

## Testcase
https://jsfiddle.net/tbkpz5cd/

**Comment by lubber-de** [comment]
This should be implemented using an optional setting like `leadingZeros:true` (at least to avoid being a breaking change).
I wonder if this new setting should also affect the input validator? So should this setting also force the user to input `02.06.2019` ?

**Comment by lubber-de** [comment]
🤔 The default formatter for dates in the calendar modules does not have the code you were referring to. The default template displays the full month name instead
https://github.com/fomantic/Fomantic-UI/blob/783786b5c27bf0252dc47c0277746b4a695210ca/src/definitions/modules/calendar.js#L1186-L1191

So i suggest to implement/support a more generic formatter option instead. Otherwise that kind of feature request is the reason why the formatter can be given dynamically as a function like you did in your fiddle.

**Comment by MarcelMpunkt** [comment]
> I wonder if this new setting should also affect the input validator? So should this setting also force the user to input `02.06.2019` ?
I think it should be optional as well.
May be there should also be a kind of **string handler** as for the year
If u input 2.6.66 it could be corrected to 02.06.1966

**Comment by lubber-de** [comment]
This is now fixed/possible by #2324 using dateformat tokens `DD.MM.YYYY`
