### ISSUE TITLE
Animation broken on first open modal with dropdown multiple

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#542]
# Bug Report

## Steps to reproduce
1. click on the first button
2. the modal open but without the animation "horizontal flip"
3. if a close and reopen the modal, the animation of modal is ok

## Expected result
open modal with animation
## Actual result
on ***first*** open modal, the animation is broken (no effect)
## Testcase
https://jsfiddle.net/dutrieux/ajwfetgh/35/

## Screenshot (when possible)
![]()
![modal](https://user-images.githubusercontent.com/1622751/53941834-72c2b080-40b9-11e9-961e-2cad63fbdafb.gif)

## Version
2.7.2

**Comment by lubber-de** [comment]
Nice catch.
You can get around this by either
- Add `queue: true` to the modal setup
- Move the dropdown initilization outside of the click event

See https://jsfiddle.net/zbvyqr2m/

**Comment by lubber-de** [comment]
Sorry, i was wrong.... forget about my last comment and the fiddle, the queuing does not seem to help/work (i take a look)
Currently it only helps to move initialization of the dropdown outside of the click event

**Comment by dutrieux** [comment]
Do you think you can fix this problem before the next release?

Thx for your help

**Comment by lubber-de** [comment]
No, featureset for 2.7.3 is complete and this isn't as easy as i thought.
Anyway is still suggest to initialize components on page load outside of further (click) events to prevent this.

**Comment by dutrieux** [comment]
I fund an other workaround with initialization of dropdown & modal on the click :

I disable the animation of the dropdown with the animation 'show' and re-enable animation 'horizontal flip' of dropdown on the onShow event :

https://jsfiddle.net/dutrieux/ajwfetgh/74/

awaiting its resolution :)

**Comment by dutrieux** [comment]
Hi @lubber-de,
Do you have a eta of this bug, do you think you could solve it for the next release or ...

**Comment by lubber-de** [comment]
@dutrieux TL;DR; No, cannot promise
As said, this isn't as easy as i thought and i still suggest doing all element initialization on page load outside of any further click events
Otherwise it seems the modal or any usage of the  transition module has to check if the current module contains any other elements as siblings which are still in animation progress and then either stop them or wait for their end... imagine there would be several elements within the modal, this could get into more trouble .
But, as always, if you have an idea how to solve this in general, don't hesitate to create a proper PR to support FUI 😃

**Comment by lubber-de** [comment]
Thanks a lot for your investigation and the provided PR!
