### ISSUE TITLE
[Popup] Popup goes beyond the screen

### ISSUE THREAD

**Issue by andrewgorpenko** [fomantic/Fomantic-UI#569]
# Help Wanted

## Problem
I am using "No Javascript" variant of the popup. I have a long text to show in it, but the problem is that the popup is not breaking the text into segments. I mean, it prints all of it in a single line.

## Test case
https://jsfiddle.net/bm1uxes3/

## Expected
Fixed width of the popup with text cropped.

## Actual
Single line text that goes beyond the screen.

**Comment by lubber-de** [comment]
This has been disussed a while back.
You can force wrapping by adding

```css
[data-tooltip]:after {
 white-space:normal;
}
```
But that would mean **all** tooltips will wrap, which is probably nor the desired behavior (and that's why we are not changing the default)
What we thought of is providing a separate data or class attribute to wrap the tooltip only at wanted elements.
An additional reason for this is, that tooltips get their width from the parent element and especially on (small/icon) buttons this would lead into very small tooltips. We would have to provide fixed min-width for those elements.
However until then here is a possible temporary fix as described above.
See https://jsfiddle.net/nzxLb2c1/

**Comment by andrewgorpenko** [comment]
Thanks for the reply. Looking forward to seeing the fix ASAP 👍
