### ISSUE TITLE
ui simple dropdown with icon only does not open on safari mobile

### ISSUE THREAD

**Issue by PhilippGrashoff** [fomantic/Fomantic-UI#570]
Hi,

2 IPhone users reported to me that my dropdown using .ui.simple.dropdown with an icon only (no text) does not work (does not expand).

Had the possibility to test that on an Iphone myself today, didnt work.
Here's a jsFiddle, but jsFiddle looks awful on mobile:
https://jsfiddle.net/hgk43dzm/

And a little html document only showing the Dropdown itself:
http://spame.de/testmenu.html

Best regards

**Comment by lubber-de** [comment]
@PhilippGrashoff 
This could be a workaround
```javascript
$('.ui.simple.dropdown')
  .on('touchstart', function(e){
  if($(e.target).parent().hasClass('simple')) {
    e.preventDefault();     
  }
});
```

I adjusted your jsfiddle accordingly:
https://jsfiddle.net/omw7z6tv/14/

Try directly in mobile safari here
https://jsfiddle.net/omw7z6tv/14/show

**Comment by PhilippGrashoff** [comment]
Hi,

My Apple testers said this fix works.

**Comment by PhilippGrashoff** [comment]
Hi, actually this fix messes up the dropdown on chrome mobile.
As this issue was closed, it does not seem to be considered a FUI bug. What be a more correct implementation of the dropdown to work the FUI way?
Best regards

**Comment by lubber-de** [comment]
Well, the suggested workaround was not considered a permanent fix.

As `simple dropdown` is supposed to be used without any javascript involved, it would be kinda confusing to implement javascript code into the FUI code to get non-javascript elements work.

I tested without the fix in chrome on android and it worked as expected.
So it seems iOS/Safari is not focussing the element automatically on click-events because icon-only elements  have no real content (the icon is displayed via pseudo-classes rather than direkt html content).
That would explain, why it works when the dropdown has additional text.

So, i suggest to use usual Javascript-dropdown boxes (`$('.ui.dropdown').dropdown()`) instead of the `simple` variant for those kinds of dropdowns.

**Comment by PhilippGrashoff** [comment]
thanks for the clarification, will use a "normal" dropdown.
Best regards
Philipp

**Comment by GammaGames** [comment]
If you like the snappy simple menus, you can use the following so it looks the same:

```javascript
$(".ui.dropdown").dropdown({
  on: "hover",
  duration: 0,
  delay: {
    show: 0,
    hide: 0
  }
});
```
