### ISSUE TITLE
[Calendar] throw specific error for unparseable date format

### ISSUE THREAD

**Issue by tjaart** [fomantic/Fomantic-UI#573]
# Bug Report

## Steps to reproduce
1.  $('#myCal').calendar()
2.  $('#myCal').calendar('set date', 'asadsadsa', true, false)

## Expected result
Error message saying that date format is invalid. 
## Actual result
Cannot read property 'getTime' of null/undefined

## Testcase
https://jsfiddle.net/m2cod85x/6/

## Version
2.7.2

**Comment by lubber-de** [comment]
An unparseable date is not fetched without a JS error by the latest v2.7.6.
As discussed and explained in https://github.com/fomantic/Fomantic-UI/pull/574#pullrequestreview-216771883 i am closing this. If many people disagree i would only agree implementing a debug statement (instead of an console error) to avoid lots of console output, which will otherwise happen too often because of the mentioned reasons in the above mentioned comment
