### ISSUE TITLE
Fullscreen Modal stuck to right edge of IE11 page

### ISSUE THREAD

**Issue by NordEirik** [fomantic/Fomantic-UI#589]
Steps
Fullscreen modal in IE11 are rendered half off-screen.
![le-modal-bug](https://user-images.githubusercontent.com/10613283/54986263-97bc8c00-4fb2-11e9-9375-ae93f70a2253.png)

Expected Result
Modal rendered full in the center of the screen.

Actual Result
Modal rendered half off screen

Version
**2.7.2**

**Comment by lubber-de** [comment]
Are you using Semantic-UI-React?

**Comment by NordEirik** [comment]
> Are you using Semantic-UI-React?
Yes. I have set up the project according to these instructions:
https://medium.com/@fomantic/setting-up-fomantic-ui-with-react-f701b68f736c

**Comment by lubber-de** [comment]
Unfortunately SUI React does not render Modals the same way SUI/FUI does (sui react did not implement the legacy option and handles multiple modals differently), so IE11 modals break as described, because of the shared CSS.

However, according to https://github.com/Semantic-Org/Semantic-UI-React/issues/3388#issuecomment-455657464 as a workround add `style={{ position: 'static' }} ` to the modal.

Anyway, this might be supported directly in FUI for SUI React by FUI 2.7.4. I already have prepared some fixes for the IE11 modal which i am still testing.

**Comment by exoego** [comment]
@lubber-de 
> I already have prepared some fixes for the IE11 modal which i am still testing.

Just a kind reminder in case the prepared PR is forgotten 😉

**Comment by lubber-de** [comment]
@exoego oh, yeah, thanks. I'll return to that by tomorrow. Thanks for the reminder 🙂

**Comment by lubber-de** [comment]
As this is related to SUI React only and we are no more supporting IE11 for dedicated bugfixes as of 2.9.0 This wont get fixed
