### ISSUE TITLE
Invalid version in file header

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#623]
# Bug Report

## Steps to reproduce
1. Go to https://cdn.jsdelivr.net/npm/fomantic-ui@2.7.4/dist/semantic.js

## Expected result

A version in file header should be `2.7.4` as same with release.

## Actual result

`2.7.2` is shown instead of `2.7.4`

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/127635/55601416-cf3dec00-579b-11e9-9ac5-5420691c4a14.png)

## Version
2.7.4

**Comment by hammy2899** [comment]
We have already been notified about this and I have checked over the files and I can confirm they are the correct files just with the wrong version number so it shouldn't affect anything. This was caused by something when we made the release which caused a few issues with the docs also.

I think we should just leave it since I don't think making a whole release just to update the dist version is worth it unless anyone else has a reason to do so.
