### ISSUE TITLE
[api]The before send function has aborted the request

### ISSUE THREAD

**Issue by apple-idn** [fomantic/Fomantic-UI#636]
# Bug Report
[api]The before send function has aborted the request

## Steps to reproduce
1.before FUI 2.7.4 is fine api
2."and now report "The before send function has aborted the request" blank blank

## Actual result
<img width="752" alt="Jepretan Layar 2019-04-07 pukul 7 19 22 PM" src="https://user-images.githubusercontent.com/33564576/55682947-91dc8880-596c-11e9-8e6b-7be5733866be.png">

## Testcase
https://jsfiddle.net/allwe/zbus396a/

## Version
2.7.4

**Comment by lubber-de** [comment]
Sorry to say, but your code is wrong. It is not related to FUI, not even when using 2.7.2.
In your "beforeSend" method your code checks, if the form itself (`this`) has a data-attribute `setuju`, which is does not have. The code, which sets that data attribute is never reached, because you are returning false beforehand, thus the mentioned console statement.

**Comment by apple-idn** [comment]
Thanks @lubber-de I will check again
