### ISSUE TITLE
[Form Validation] search selection dropdown with rule type 'empty' validates on form clear or form reset.

### ISSUE THREAD

**Issue by 5t4r8ucK** [fomantic/Fomantic-UI#778]
# Bug Report
[Form Validation] search selection dropdown with rule type 'empty' validates on form clear or form reset.

## Steps to reproduce
1. Create a form with a search selection dropdown in it.
2. Create validation rules for the field and search selection dropdown of type 'empty'.
3. Create a button to clear/reset the form (or create a submit button with a call to clear/reset the form on submission)
4. Fill in the form, including the search-selection dropdown.
5. Press the clear/reset button (or submit the form if on submission the form clears/resets)

## Expected result
If a form is cleared or reset then all the fields in the form, including the search selection dropdown, should clear their data and remove error messages.

## Actual result
Instead of clearing the data from the search selection dropdown, like it does for the regular inputs, the form runs validation on the search selection dropdown and then displays an error.

## Test case
https://jsfiddle.net/St4r8ucK/ukdLbe08/25/

## Screenshot (when possible)
![Capture](https://user-images.githubusercontent.com/39564849/58467449-f8e01780-813b-11e9-909c-ed10829f5923.PNG)

## Version
2.7.5

**Comment by lubber-de** [comment]
After looking at the code, it turns out the docs are not up to date.
The provided `input` field won't be correctly recognized as search input and the module always creates a second input field.

To fix this you have 2 options:

- remove the `type=hidden`   and add `class="search"`  to the `input` field
https://jsfiddle.net/sbk9w4dt/
 __or__
- remove the entire `input field`, it will be created by the module automatically
https://jsfiddle.net/sbk9w4dt/1/

**Comment by lubber-de** [comment]
🤔 mmh, tested again, my suggested fix is not accurate enough, the form validation won't find the input at all to validate it.... I think, we definately have to fix something here in the code. Also the docs are fine (the hidden input was a value holder only instead of meant to be used as search input, my fault..)

**Comment by lubber-de** [comment]
Finally fixed by #1092
See your adjusted jsfiddle here https://jsfiddle.net/y6qmp8bd/
