### ISSUE TITLE
[Form] Transparent left icon input

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#798]
# Bug Report

## Steps to reproduce
1. Create a form
2. Add a field with transparent left icon input
3. Padding is 1em instead of 2em

## Expected result
Should have padding for the icon

## Actual result
Input is smushed against the icon

Might be happening because more precise rule doesn't take into account transparent icon padding

## Testcase
https://jsfiddle.net/2tLh840s/

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/7832163/58987105-16485d80-879c-11e9-8f94-6c88616a9eb7.png)

## Version
2.7.5

**Comment by lubber-de** [comment]
Fixed by #801 
See your adjusted jsfiddle here https://jsfiddle.net/wdz41Lqu/

**Comment by aardbol** [comment]
This release messes up the transparent inputs I use though. The padding is by default too much. Have a look:

**FUI 2.7.5**
![2019-06-19 11_19_03-Window](https://user-images.githubusercontent.com/14614620/59753674-ed889380-9284-11e9-8b7b-fa7164b08178.png)

**FUI 2.7.6**
![2019-06-19 11_24_52-Window](https://user-images.githubusercontent.com/14614620/59753683-efeaed80-9284-11e9-8121-271f5e3aa11f.png)

Now I have to tweak the padding myself to force a decent layout, but that's not a good approach, as the lies in the default layout.

I understand that the bottom padding is only noticeable because of my underlining and maybe you don't consider that an issue. But still the left padding remains a big issue for inputs without an icon.

**Comment by lubber-de** [comment]
@aardbol Please provide a jsfiddle for easier investigation and to see how you implemented it, because the padding is wanted behavior when inputs are used within forms for consistent behavior.
However, if you use the transparent inputs outside of a form the padding should not be there.

**Comment by aardbol** [comment]
As requested:

https://jsfiddle.net/pwzh7gs4/

I find it weird that even though it's inside a form, it's padding like that though. Padding is not bad per se, but imo the way it's implemented looks messy. The height (padding) is invisible to the user, but the left padding isn't

**Comment by lubber-de** [comment]
@aardbol Thanks for the jsfiddle.
Well, the reason for general padding of input fields in forms was a consistent look especially when fields get the `error` class. #801 was just continuing to apply the consistent look.
See our previous discussion about that topic here https://github.com/fomantic/Fomantic-UI/issues/107

However, i understand your desired behaviour, but i think that means we have to invent another class, like `compact transparent input`, to support zero-padding inputs within forms also (with the possibly mentioned visual issues when an error class is applied)
What you can do in the meantime of course is to adjust `@transparentPadding` in `form.variables` to your needs (`0` then)

Anyway, I adjusted your fiddle though: https://jsfiddle.net/aeq7wL9k/
