### ISSUE TITLE
Checkbox changes state on ENTER key

### ISSUE THREAD

**Issue by maibaum007** [fomantic/Fomantic-UI#819]
Current behavior: Checkboxes change their status, when they are focused and the ENTER-Key is pressed.

Expected behavior: They should only react to space key as native checkboxes do.

Problem: ENTER-Key is used to commit forms.  Now, when you commit a form with ENTER-Key, the value of the checkbox changes unintentionally.

EDIT: Only happens, when checkbox gets initialized via Javascript

**Comment by lubber-de** [comment]
Unfortunately i cannot reproduce this. See my testcase here
https://jsfiddle.net/7kqL485z/
When the checkbox gets clicked/focused , pressing RETURN does nothing as expected, but SPACE does.

Could you please adjust the jsfiddle to make the behavior reproducable, so we can investigate?
Thank you.

**Comment by lubber-de** [comment]
Nevermind, can reproduce now. It happens when checkox gets initialized via Javascript.
Testcase https://jsfiddle.net/s4pmq7o1/

**Comment by lubber-de** [comment]
Adjustable via new setting `enableEnterKey: false` by #824 
I labeled this issue as enhancement instead of a bug, because the functionality of being able to also use the ENTER key is implemented since a long time and therefore considered wanted behavior. Thus, the new setting of enabled by default to avoid a breaking change.
See https://jsfiddle.net/6o8pvfe4/
