### ISSUE TITLE
[cards] horizontal cards too far in mobile view

### ISSUE THREAD

**Issue by ghost** [fomantic/Fomantic-UI#828]
I switched from Semantic UI to the latest version of Fomantic-UI and changed some things because of your changes in my web application.

If I go to horizontal cards in the mobile view, I noticed that the width is too far.
![Capture](https://user-images.githubusercontent.com/47126617/59915563-307d6f00-941d-11e9-8a6a-49b4c4b81699.PNG)

**Comment by lubber-de** [comment]
@FFDevelopment 
Could you please provide some jsfiddle ? Because i cannot reproduce any wrong width behavior.
See a prepared jsfiddle here https://jsfiddle.net/6wu3mj9b/
The cards wrap as expected when they do not fit horizontally in one row. Of course this lead into a right empty area, but just because the second card does not fit anymore.
Is this, what you are talking about? If so, what would the expected behavior in your opinion? 
![horizontal_cards_wrap](https://user-images.githubusercontent.com/18379884/59943761-5a598480-9463-11e9-9753-387b78c0cc60.gif)

**Comment by lubber-de** [comment]
Ok, i think i understood: I tried my example in an iphone 5 view, then it is getting clear.
![image](https://user-images.githubusercontent.com/18379884/59945017-97734600-9466-11e9-8f76-51ea0b9d9fc7.png)

**Comment by FFDevelopment** [comment]
Sorry that I didn't write that I mean the mobile view in the browser.

**Comment by lubber-de** [comment]
Fixed by #1145
