### ISSUE TITLE
[Form] Form cannot submit if a form contains select dropdown with required attribute and leaves empty

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#917]
# Bug Report
The form failed to submit when it contains the HTML select element with the "required" attribute which uses Fomantic dropdown and the select left empty.

## Steps to reproduce
1. Create a form including the select element with the attribute "required"
2. Add the options for the select element. Include also for the empty option.
3. Invoke the dropdown plugin to the select element.
4. Submit the form.
5. The form fails to submit. In the browser console, the error "An invalid form control with name='' is not focusable" appears.

## Testcase
Here's the fiddle https://jsfiddle.net/ndpuks2y/2/

## Version
2.7.6

Having this issue on Firefox (68) and Chrome (75.0.3770.90) on Ubuntu. Firefox doesn't show any error but prevents the form submission.

## Note
According to this [post](https://stackoverflow.com/questions/7168645/invalid-form-control-only-in-google-chrome/7264966#7264966) on Stackoverflow, the select should remove the attribute "required" which is hidden by Javascript, in our case, the select element with dropdown component shouldn't have the attribute "required".

**Comment by lubber-de** [comment]
I fixed this basically by #920 , but i am unsure if we should really do this:

- Using `required` in a select-tag when using FUI could be considered unusual/unsupported logic, because FUI has its form validation instead
- As it probably breaks code, it has to wait until 2.8.0: Some people probably have used this already and , to be honest, it does what it should: it prevents the form submission if you do not select anything (and "empty" is basically meant as the placeholder, not a valid entry (and even if: Why should one define it as "required" then?))
- The log warning does not prevent other Javascript to be executed

More thoughts about that is found in the PR

I labeled this as an enhancement instead of a bug because of the mentioned reasons

**Comment by ko2in** [comment]
My problem solved with `novalidate` attribute in form as mentioned in #920. Should I close this issue myself?

**Comment by lubber-de** [comment]
No, let's wait for other contributors opinion of the related PR, please
