### ISSUE TITLE
Issue when adding item to existing dropdown and using $('#dropdown').dropdown('set selected', 'xx')

### ISSUE THREAD

**Issue by jprateragg** [fomantic/Fomantic-UI#919]
I recently ran into an issue with Fomantic-UI in which I'm adding an entry to an already created dropdown (using an HTML `select`), then making it the selected entry. I finally found a workaround on the Semantic-UI issues: https://github.com/Semantic-Org/Semantic-UI/issues/5516#issuecomment-502929515

The workaround does work, but it would be nice to not have to use a timeout whenever I dynamically add an entry to an existing dropdown. I was just curious if this could be fixed somehow. Thanks.

**Comment by maidzen** [comment]
i tried to reproduce it but it works for me in Chrome/Firefox and Edge ...

https://jsfiddle.net/xzq9pojm/3/

**Comment by jprateragg** [comment]
https://jsfiddle.net/b53ju1L4/ I change this `$('.dropdown').dropdown('set selected', '2');` and when you try it again, option 2 isn't selected. Just option 1.

**Comment by lubber-de** [comment]
I could reproduce in Firefox mobile.
The problem is: The mutationobserver, which recognizes your DOM changes (and has to rebuild the FUI dropdown HTML code) seems to be too slow there.
So, by the time you are calling `$('.dropdown').dropdown('set selected', '2');` the necessary changes for the dropdown DOM has not finished (or not even started) rebuilding the Dropdown HTML Code according to your node-changes, so the value "2" does not exist, thus not being selected.
That's why the workaround using a timeout is working.

But: Instead of changing the option value dom nodes yourself you can use the behavior `change values`
That approach does not need a workaround and seems to work as expected.
I adjusted your example jsfiddle here: https://jsfiddle.net/6tge5q13/

**Comment by lubber-de** [comment]
As we cannot change the way MutationObserver is implemented in different browsers. If you still have to change the DOM nodes, you either have to use the settimeout or the `change values` behavior solution. I dont't think we can handle that otherwise within the framework. 
If anyone comes up with another solution, we can reopen this
